### ISSUE TITLE
Unable to run in docker on ARM Mac

### ISSUE THREAD

**Issue by adeffur** [Cinnamon/kotaemon#132]
When using the following to run kotaemon in docker, the container exits. (Host is M2 Mac with Rosetta)

`docker run --platform linux/amd64 -e GRADIO_SERVER_NAME=0.0.0.0 -e GRADIO_SERVER_PORT=7860 -p 7860:7860 -it taprosoft/kotaemon:v1.0`

The following output is printed to the screen:

> Warning: Cannot statically find a gradio demo called demo. Reload work may fail.
Watching: '/app' '/app'
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /usr/local/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

Not sure what I'm missing.

**Comment by smshapiro85** [comment]
Same on my end

**Comment by smshapiro85** [comment]
<img width="687" alt="image" src="https://github.com/user-attachments/assets/61a45129-0487-447a-9db5-8bffaa102fd9">

I tried to run it on my synology NAS with the same error, so it may not be related to ARM Mac only

**Comment by taprosoft** [comment]
Should be able to do this on Mac ARM. Let us work on this issue to check if is reproducible.

**Comment by sturdan** [comment]
same error here windows x64 using docker desktop

**Comment by taprosoft** [comment]
Can you use `docker logs` to check out what might be the possible issue.

**Comment by kintopp** [comment]
I see this too on MacMini M2 Pro, OSX 14.6.1. Docker Desktop v4.33.0. Same error as others in this thread: 

> Warning: Cannot statically find a gradio demo called demo. Reload work may fail.
> Watching: '/app' '/app'

`docker logs -f <container>` shows the same error, no other messages. `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check` passes all tests.

**Comment by sturdan** [comment]
same `docker logs` message on windows x64 and docker desktop (having an old CPU without AVX, x5650)

> Warning: Cannot statically find a gradio demo called demo. Reload work may fail.
> Watching: '/app' '/app'
> [nltk_data] Downloading package punkt_tab to
> [nltk_data] /usr/local/lib/python3.10/site-
> [nltk_data] packages/llama_index/core/_static/nltk_cache...
> [nltk_data] Unzipping tokenizers/punkt_tab.zip.

**Comment by RobTranquillo** [comment]
Same here on M3 Macbook Pro in Docker in Terminal as well as Docker Desktop (freshly installed). Never used Docker on this machine.

**Comment by byronbowerman** [comment]
Same results; M1 MacBook Pro + Orbstack 1.7.0

**Comment by taprosoft** [comment]
Noted. Seem this a common issues. Please wait why we investigate this issue.

**Comment by Aplhasixty** [comment]
Same results: M2 macbook pro

**Comment by sturdan** [comment]
would guess it is AVX relatead, all CPU's listed here missing it

**Comment by jborbik** [comment]
That's my output on a M2 MacBook:
```
$ docker run -e GRADIO_SERVER_NAME=0.0.0.0 -e GRADIO_SERVER_PORT=7860 -p 7860:7860 -it --rm taprosoft/kotaemon:v1.0

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Warning: Cannot statically find a gradio demo called demo. Reload work may fail.
Watching: '/app' '/app'

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /usr/local/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
```
I managed to resolve the first warning by explicitly specifying the platform but the docker container still closes immediately and the website is not available:
```
$ docker run --platform linux/amd64  -e GRADIO_SERVER_NAME=0.0.0.0 -e GRADIO_SERVER_PORT=7860 -p 7860:7860 -it --rm taprosoft/kotaemon:v1.0


Warning: Cannot statically find a gradio demo called demo. Reload work may fail.
Watching: '/app' '/app'

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /usr/local/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
```

**Comment by pathros** [comment]
Same here. On MacOS apple silicon, i get the following error:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
when trying:
```
docker run -e GRADIO_SERVER_NAME=0.0.0.0 -e GRADIO_SERVER_PORT=7860 -p 7860:7860 -it --rm taprosoft/kotaemon:v1.0
```
Any ideas to fix it ad make it work?

complete output:
```
> docker run -e GRADIO_SERVER_NAME=0.0.0.0 -e GRADIO_SERVER_PORT=7860 -p 7860:7860 -it --rm taprosoft/kotaemon:v1.0
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Warning: Cannot statically find a gradio demo called demo. Reload work may fail.
Watching: '/app' '/app'

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /usr/local/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
```

moreover:
```
docker: image with reference docker.io/taprosoft/kotaemon:v1.0 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64.
```

**Comment by slimandslam** [comment]
Same issues -- M1 MacBook Pro running MacOS Sonoma 14.6.1

**Comment by MarcCG0** [comment]
Same issue here on my M2 Max mac, MacOS 13.0 Ventura

**Comment by adeffur** [comment]
FYI
Used the same command on a Ryzen-based system running Win10, started as expected. So probably a CPU compatibility issue. Apparently macOS Sonoma will bring AVX support to Apple Silicon machines.

**Comment by bookandlover** [comment]
Same issue. Cannot run on Mac M2 Max.

**Comment by adeffur** [comment]
> FYI Used the same command on a Ryzen-based system running Win10, started as expected. So probably a CPU compatibility issue. Apparently macOS Sonoma will bring AVX support to Apple Silicon machines.

Correction: macOS **Sequoia** is bringing support for AVX2 ([source](https://apple.stackexchange.com/questions/419554/can-i-get-avx-support-on-my-new-macbook-air-m1-cpu)) (currently available in the beta). Not sure which level is required for the kotaemon container to run. Also found no mention of AVX512 support in macOS Sequoia.

**Comment by yby2003** [comment]
Same issue. Cannot run on Mac M2 Ultra.

**Comment by RicardoMonteiroSimoes** [comment]
They added the github action to auto build docker images, I have a PR open to add ARM image support https://github.com/Cinnamon/kotaemon/pull/226

**Comment by trahloff** [comment]
Same for Synology NAS (Intel Celeron J4125, no AVX support)

**Comment by cin-niko** [comment]
Resolved in the new version. Please check the latest docker `full` for amd64.
