### ISSUE TITLE
cannot install(non technical)

### ISSUE THREAD

**Issue by michaelyeung445** [Cinnamon/kotaemon#136]
Collecting git+https://github.com/Cinnamon/kotaemon.git@v0.3.6
  Cloning https://github.com/Cinnamon/kotaemon.git (to revision v0.3.6) to c:\users\micha\appdata\local\temp\pip-req-build-5dizcuak
  ERROR: Error [WinError 2] 系統找不到指定的檔案。 while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by lone17** [comment]
the installation package for non-tech users is quite out dated and the team are working on it. In the meantime, if you are comfortable with running git and python, please check out this guide #138

**Comment by michaelyeung445** [comment]
maybe too complex for me. can you notify me when the package is updated?

**Comment by lone17** [comment]
please watch the repo, github will send you a notification when a new release is created.

**Comment by zono50** [comment]
When i install using docker, i went into ollama and changed localhost to host.docker.internal, but still getting this error.

tenacity.RetryError: RetryError[<Future at 0x72a5443ba230 state=finished raised AuthenticationError>]

**Comment by lone17** [comment]
@zono50 seems to be related to #143, can you try the fix proposed there ?

**Comment by taprosoft** [comment]
@zono50 can you try https://github.com/Cinnamon/kotaemon/issues/143#issuecomment-2316974363?
