### ISSUE TITLE
[BUG] - Error when installing graphrag

### ISSUE THREAD

**Issue by qdubois** [Cinnamon/kotaemon#142]
### Description

I have an error when installing graphrag.
in order to run graphrag I try to run 
`pip install graphrag future` But get the following error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.

### Reproduction steps

```bash
1. Go to 'project root folder'
2. Run on 'pip install graphrag future'
3. Get the error: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
```

### OS

MacOS

**Comment by taprosoft** [comment]
It okay to just run `pip install graphrag future` after installing all kotaemon base requirement and ignore those version conflict. Since `graphrag` base package continuously update their pipeline, we will work on a stable setup script when it features are stable.

**Comment by qdubois** [comment]
Thanks. for your quick answer.

After ignoring the error indexing a file and trying to chat with, I got the an error regarding a missing output : 

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/_dev/my_company/kotaemon/ktem_app_data/user_data/files/graphrag/51415a47-7095-470c-862e-92918ccbbd94/output'
Updating retrieval history (regen=True)
User-id: 1, can see public conversations: True
```

any idea?

Thanks for your help

**Comment by taprosoft** [comment]
Seem GraphRAG indexing is not working well. Please check this issue for more insight on setting up the env var required for GraphRAG :D

https://github.com/Cinnamon/kotaemon/issues/140

Also, please check the log of indexing process to see if there is any thing happened abnormally.

**Comment by arbazw** [comment]
hi, please try the following steps:

1. use a virtual environment. this helps avoid conflicts with system-wide packages:
   ```
   python3 -m venv env
   source env/bin/activate
   ```

2. if the above didn't work, try installing each package separately to identify conflicts:
   ```
   pip install graphrag
   pip install future
   ```

3. you can also use the `--verbose` flag with pip for more detailed error messages:
   ```
   pip install graphrag future --verbose
   ```

hope this helps!

**Comment by Sere1nz** [comment]
ERROR: No matching distribution found for graphrag
![image](https://github.com/user-attachments/assets/a7a33350-4422-4ba3-a3e2-edbcfb75ae96)

**Comment by cefege** [comment]
> ERROR: No matching distribution found for graphrag ![image](https://github.com/user-attachments/assets/a7a33350-4422-4ba3-a3e2-edbcfb75ae96)

I have the exact same issue
