### ISSUE TITLE
[REQUEST] - Docker image for arm architectures

### ISSUE THREAD

**Issue by maxkonrad** [Cinnamon/kotaemon#145]
### Summary

As it seems in https://hub.docker.com/r/taprosoft/kotaemon/tags there is no docker image for arm arch. Waiting for it

### Basic Example

I want to pull it to my raspi4b and deploy it there, but need to find an another solution for now.

### Drawbacks

idk

**Comment by pathros** [comment]
Same here. On MacOS apple silicon, i get the following error:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
when trying:
```
docker run -e GRADIO_SERVER_NAME=0.0.0.0 -e GRADIO_SERVER_PORT=7860 -p 7860:7860 -it --rm taprosoft/kotaemon:v1.0
```
Any ideas to fix it ad make it work?

**Comment by stephanj** [comment]
Adding "--platform linux/amd64" to the docker command gets rid of the warning:

```
docker run --platform linux/amd64 -e GRADIO_SERVER_NAME=0.0.0.0 -e GRADIO_SERVER_PORT=7860 -p 7860:7860 -it --rm taprosoft/kotaemon:v1.0
```

However the next issue is:

```
Warning: Cannot statically find a gradio demo called demo. Reload work may fail.
Watching: '/app' '/app'
```

**Comment by lethal233** [comment]
Same issue here:
```bash
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Warning: Cannot statically find a gradio demo called demo. Reload work may fail.
Watching: '/app' '/app'
```

Env:
MacOS Sequoia 15.1 dev beta (24B5035e)

**Comment by slimandslam** [comment]
Same issue. Macbook Pro M1. MacOS Sonoma 14.6.1

**Comment by RicardoMonteiroSimoes** [comment]
Same here, whilst emulating is a possible solution, it's make it so unbearably slow that it wouldn't be worth the usage.

**Comment by mintisan** [comment]
+1

**Comment by bartmch** [comment]
To build the image for an ARM architecture, in the same repo as the Dockerfile run: 
`docker build --platform linux/arm64 -t taprosoft/kotaemon:arm64 .`

**Comment by RicardoMonteiroSimoes** [comment]
Does anyone know what the relation of `taprosoft` and this repository is? It appears that the builds are done externally and there for don't have to be the same as here. Potentially this could be enhanced with a `kotaemon` account on docker hub and push built dockerfiles directly each release?

**Comment by bartmch** [comment]
For those concerned about emulating architectures, you can just create your Dockerfile based on the main repo's Dockerfile. Below Dockerfile creates an ARM-architecture images:

```
#syntax=docker/dockerfile:1.0.0-experimental
FROM python:3.10-slim as base_image

#Install system dependencies
RUN apt-get update -qqy && \
    apt-get install -y --no-install-recommends \
    ssh \
    git \
    gcc \
    g++ \
    poppler-utils \
    libpoppler-dev \
    curl \
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

#Install Rust and Cargo
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
    && . "$HOME/.cargo/env" \
    && rustup default stable

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

#Use the base image for development
FROM base_image as dev

#Copy the entire application code
COPY . /app

#Install Python dependencies
RUN --mount=type=ssh pip install --no-cache-dir -e "libs/kotaemon[all]" \
    && pip install --no-cache-dir -e "libs/ktem" \
    && pip install --no-cache-dir graphrag future \
    && pip install --no-cache-dir "pdfservices-sdk@git+https://github.com/niallcm/pdfservices-python-sdk.git@bump-and-unfreeze-requirements"

#Set the entry point for the Gradio application
ENTRYPOINT ["gradio", "app.py"]
```

After running the container you can check the architecture with:
`docker inspect --format='{{.Os}}/{{.Architecture}}' taprosoft/kotaemon:arm64`

**Comment by slimandslam** [comment]
> To build the image for an ARM architecture, in the same repo as the Dockerfile run: `docker build --platform linux/arm64 -t taprosoft/kotaemon:arm64 .`

This fails on my M1 Mac Pro running MacOS 14.6.1.  It says that rust and cargo are not found but I use rust and cargo every day, so they are most definitely in the PATH.  Log attached.

[log.txt](https://github.com/user-attachments/files/16857741/log.txt)

**Comment by cin-niko** [comment]
> This fails on my M1 Mac Pro running MacOS 14.6.1. It says that rust and cargo are not found but I use rust and cargo every day, so they are most definitely in the PATH. Log attached.

@stephanj, if you still have problems with cargo, please try it: https://github.com/Cinnamon/kotaemon/issues/172#issuecomment-2330675986.  (just install cargo in Docker)
It works with me.

**Comment by phv2312** [comment]
@RicardoMonteiroSimoes taprosoft is one of the first creators and the main PIC for this open-source project from the beginning.
Sorry for the inconvenience, we are working to standardize the progress, includes the Docker too.

**Comment by taprosoft** [comment]
@RicardoMonteiroSimoes sorry for the late reply. We already created CI/CD flow to automatically build and push Docker images to Kotaemon repo upon release. For my role, currently I am the main maintainer of this repo and provide manual build for previous release on my personal repo. However, it will be migrated (with new instruction on README) soon. Stay tuned.

**Comment by RicardoMonteiroSimoes** [comment]
Sounds cool, thanks a lot for your work!

**Comment by RicardoMonteiroSimoes** [comment]
saw the github action added, decided to help out https://github.com/Cinnamon/kotaemon/pull/226
