### ISSUE TITLE
RetryError

### ISSUE THREAD

**Issue by yaozeyang90** [Cinnamon/kotaemon#148]
### Description

tenacity.RetryError: RetryError[<Future at 0x7facc8713520 state=finished raised APIStatusError>]

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by taprosoft** [comment]
Please add more info to support diagnose your issue.
If you are using ollama, check:
https://github.com/Cinnamon/kotaemon/issues/143#issuecomment-2316974363

If you are using OpenAI API, make sure that OPENAI_API_KEY env variable are set in .env file correctly.
