### ISSUE TITLE
A Communication Group （建一个交流群）

### ISSUE THREAD

**Issue by chmod777john** [Cinnamon/kotaemon#151]
It's a great job! How about creating a community group ?

I have created a Discord group, click to join. I suggest the author include this link in the Readme. There’s no ill intent in creating this group, and if the author needs it, I’m willing to transfer the group admin position.

https://discord.gg/h57gYkQ38A

For Chinese users, you can also Join the Wechat group. (Chinese: 中国同胞可以加下面这个群，失效请联系微信 dreamingforhope )
![image](https://github.com/user-attachments/assets/46dabd31-0f18-4dc0-bd2e-58fc38c98548)

**Comment by lone17** [comment]
Thank you for your support ! But I'm not sure if the team have the bandwidth to handle a discord cc @taprosoft . Maybe enable Github Discussion instead ?

**Comment by chmod777john** [comment]
Both is ok! I just found many trending projects have their community group. Eg: https://github.com/nocodb/nocodb

Sometimes people's real-time discussion may bring new ideas

**Comment by lone17** [comment]
Yeah I understand and also have thought about it. But the team is really thin, it might mostly be users helping each other I'm afraid. But ultimately, let's have @taprosoft and the team decide this.

**Comment by taprosoft** [comment]
May be we have to assign a community manager for this @lone17 ... But let see what we can do.

**Comment by cin-jimmy** [comment]
Good suggestion, @chmod777john 
We'll work on that.

**Comment by WangAo-0** [comment]
群过期呢
