### ISSUE TITLE
What is the difference between kotaemon and other RAG apps? 

### ISSUE THREAD

**Issue by chmod777john** [Cinnamon/kotaemon#154]
There are many RAG apps before.
How is kotaemon compared to them? 
Eg: 
https://github.com/Mintplex-Labs/anything-llm
https://github.com/weaviate/Verba
https://github.com/infiniflow/ragflow
(many other RAGs not listed yet)

**Comment by taprosoft** [comment]
Hi @chmod777john, we also have done a comprehensive review of available RAG apps with webUI, here are the thing that we believe `kotaemon` is different:

* Inclusion of direct PDF preview in the web UI, together with highlighting of relevant sentences (through citation function call from LLM). This greatly help to double check the context of LLM and make sure generated answer contains fact or hallucination.
* Support complex reasoning methods. We aims to support agent-based reasoning like: question decomposition to answer multi-hop question, ReAct, ReWOO (and others like MemoryGIST and GraphReader which is WIP).
* Configurable prompt in settings. You can adjust most important aspects of retrieval & generation process on the UI (incl. prompts).
* Extensible. Based on Gradio, if you have experience with it, it is easy to add or remove your UI component to feed any customization (e.g: new input / output) for your custom RAG pipeline. We demonstrate this with custom graph view when using GraphRAG retriever.

Hope this help!

**Comment by DeveloperVaibhav1** [comment]
could you pls clearify the text mention above
