### ISSUE TITLE
[BUG] - GraphRAG dependencies is not link.

### ISSUE THREAD

**Issue by kientranasia** [Cinnamon/kotaemon#164]
### Description

Please help to guide how to install the GraphRAG and Link with Kotatemon on Ollama.

I am using the enduser Application

![CleanShot 2024-08-31 at 17 37 22@2x](https://github.com/user-attachments/assets/fc29c777-9137-485a-b4ae-72fa8637c17b)

### Reproduction steps

```bash
1. Run Kotaemon with EndUser version (not dev) (run_macos.sh)
2. After running it show "GraphRAG dependencies not installed. GraphRAG retriever pipeline will not work properly.
"
3. The GraphRAG not working
```

**Comment by phv2312** [comment]
I found the similar issue here and got resolved, can you check? https://github.com/Cinnamon/kotaemon/issues/140#issuecomment-2320643924
