### ISSUE TITLE
libmagic error and value error after running pytests

### ISSUE THREAD

**Issue by chiragml** [Cinnamon/kotaemon#169]
### Description

I tried to set the repo up because I wanted to try contributing however I'm facing the following errors while running the pytests. I tried checking online but I can't find anything that fixes this. Can anyone help with this please? 
![error](https://github.com/user-attachments/assets/577fe046-1eee-4ddf-9211-9c63f36a0742)

### Reproduction steps

```bash
FAILED tests/test_ingestor.py::test_ingestor_include_src - ValueError: Metadata length (100046) is longer than chunk size (200). Consider increasing the chunk size or decreas...
FAILED tests/test_reader.py::test_html_reader - UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 259: character maps to <undefined>
FAILED tests/test_reader.py::test_unstructured_pdf_reader - ImportError: failed to find libmagic.  Check your installation
FAILED tests/test_table_reader.py::test_ocr_reader - ImportError: failed to find libmagic.  Check your installation
```

### Screenshots

```bash
![error](https://github.com/user-attachments/assets/577fe046-1eee-4ddf-9211-9c63f36a0742)
```

### OS

Windows

### Additional information

I kinda tried everything on google that I could find on this but nothing worked.

**Comment by phv2312** [comment]
Hi, libmagic is the dependency of unstructured package. Following the docs from unstructured https://docs.unstructured.io/open-source/installation/full-installation. You may need to install some ubuntu dependencies like: [libmagic](https://man7.org/linux/man-pages/man3/libmagic.3.html), [poppler](https://poppler.freedesktop.org/), [libreoffice](https://www.libreoffice.org/discover/libreoffice/), [pandoc](https://pandoc.org/), and [tesseract](https://github.com/tesseract-ocr/tesseract)

Can you try to install the libmagic as suggested below and run pytest again ?
```
sudo apt-get install -y libmagic-dev poppler-utils libreoffice
```

Besides, in the Dockerfile we have commented out some extra packages, install all will help support all file types [include unstructured] but take more storage https://github.com/Cinnamon/kotaemon/blob/main/Dockerfile#L6

**Comment by arbazw** [comment]
hi, try the following steps;

1. try modifying the chunk size in the configuration or code if it's hard-coded. if it’s configurable, increase it to a value higher than 100046. if the metadata length is configurable, you could also try decreasing it.

2. modify the test or the code being tested to explicitly specify the encoding, usually `UTF-8`. Look in `tests/test_reader.py` for the `test_html_reader` function and add `encoding='utf-8'` to any open file operations

3. you need to ensure that libmagic is correctly installed. use `pip install python-magic-bin`, but you may also need to manually install the libmagic binaries.

after applying these changes, re-run the tests using `pytest`

**Comment by chiragml** [comment]
That worked thank you so much.

**Comment by osgoh88** [comment]
> hi, try the following steps;
> 
> 1. try modifying the chunk size in the configuration or code if it's hard-coded. if it’s configurable, increase it to a value higher than 100046. if the metadata length is configurable, you could also try decreasing it.
> 2. modify the test or the code being tested to explicitly specify the encoding, usually `UTF-8`. Look in `tests/test_reader.py` for the `test_html_reader` function and add `encoding='utf-8'` to any open file operations
> 3. you need to ensure that libmagic is correctly installed. use `pip install python-magic-bin`, but you may also need to manually install the libmagic binaries.
> 
> after applying these changes, re-run the tests using `pytest`

I have similar issue. 
![GraphRAG error](https://github.com/user-attachments/assets/4d3432d1-6f5e-471b-9a72-1a60219944ca)

I followed your steps, but they are still not working. 
Where to add `encoding='utf-8'? it is in the C:\kotaemon\libs\kotaemon\tests\test_reader.py?
Thanks
