### ISSUE TITLE
[BUG] - <title>NO MODULE NAMED "KOTAEMON" in Window 10 

### ISSUE THREAD

**Issue by vinhinnovation** [Cinnamon/kotaemon#171]
### Description

![image](https://github.com/user-attachments/assets/c10f5e04-d74d-4d82-b1b8-ed180a8b807f)
NO MODULE NAMED "KOTAEMON" in Window 10 

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by phv2312** [comment]
Hi, can you remove the `install_dir` and reinstall again? And during the install can you share us the logs if error occurs ?

**Comment by ikunchickchick** [comment]
same error。i tried you advice that delete the install_dir and install again.here is logs.
******************************************************
Setting up Miniconda
******************************************************

Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 85.5M  100 85.5M    0     0  3370k      0  0:00:26  0:00:26 --:--:-- 4179k
Installing Miniconda to C:\Users\admin\Downloads\kotaemon-app\install_dir\conda
Conda is installed at C:\Users\admin\Downloads\kotaemon-app\install_dir\conda
Conda version:
conda 24.7.1

******************************************************
Creating conda environment
******************************************************

Creating conda environment with python=3.10 in C:\Users\admin\Downloads\kotaemon-app\install_dir\env
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\admin\Downloads\kotaemon-app\install_dir\env

  added / updated specs:
    - python=3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-24.2                   |  py310haa95532_0         2.5 MB
    python-3.10.14             |       he1021f5_1        15.9 MB
    setuptools-72.1.0          |  py310haa95532_0         2.5 MB
    wheel-0.43.0               |  py310haa95532_0         136 KB
    ------------------------------------------------------------
                                           Total:        21.0 MB

The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/win-64::bzip2-1.0.8-h2bbff1b_6
  ca-certificates    pkgs/main/win-64::ca-certificates-2024.7.2-haa95532_0
  libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_1
  openssl            pkgs/main/win-64::openssl-3.0.14-h827c3e9_0
  pip                pkgs/main/win-64::pip-24.2-py310haa95532_0
  python             pkgs/main/win-64::python-3.10.14-he1021f5_1
  setuptools         pkgs/main/win-64::setuptools-72.1.0-py310haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.45.3-h2bbff1b_0
  tk                 pkgs/main/win-64::tk-8.6.14-h0416ee5_0
  tzdata             pkgs/main/noarch::tzdata-2024a-h04d1e81_0
  vc                 pkgs/main/win-64::vc-14.40-h2eaa2aa_0
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.40.33807-h98bb1dd_0
  wheel              pkgs/main/win-64::wheel-0.43.0-py310haa95532_0
  xz                 pkgs/main/win-64::xz-5.4.6-h8cc25b3_1
  zlib               pkgs/main/win-64::zlib-1.2.13-h8cc25b3_1



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate C:\Users\admin\Downloads\kotaemon-app\install_dir\env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Conda environment created successfully
Activate conda environment at C:\Users\admin\Downloads\kotaemon-app\install_dir\env

******************************************************
Installing Kotaemon
******************************************************

Installing Kotaemon v0.4.3
Collecting git+https://github.com/Cinnamon/kotaemon.git@v0.4.3#subdirectory=libs/kotaemon
  Cloning https://github.com/Cinnamon/kotaemon.git (to revision v0.4.3) to c:\users\admin\appdata\local\temp\pip-req-build-hxwkjnmz
  ERROR: Error [WinError 2] 系统找不到指定的文件。 while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
Collecting git+https://github.com/Cinnamon/kotaemon.git@v0.4.3#subdirectory=libs/ktem
  Cloning https://github.com/Cinnamon/kotaemon.git (to revision v0.4.3) to c:\users\admin\appdata\local\temp\pip-req-build-qq_se2ul
  ERROR: Error [WinError 2] 系统找不到指定的文件。 while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
Collecting git+https://github.com/Cinnamon/kotaemon.git@v0.4.3
  Cloning https://github.com/Cinnamon/kotaemon.git (to revision v0.4.3) to c:\users\admin\appdata\local\temp\pip-req-build-8qs_z0ri
  ERROR: Error [WinError 2] 系统找不到指定的文件。 while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

Installation failed. You may need to run the installer again.
Deactivate conda environment at C:\Users\admin\Downloads\kotaemon-app\install_dir\env
请按任意键继续. . .

**Comment by phv2312** [comment]
The second error message show that you have a problem with git. Can you help to install the git by document here https://git-scm.com/download/win .
Remember to add it to your PATH enviroment variable if necessary.

**Comment by phv2312** [comment]
I found some similar issue on another repo and got resolved here https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/issues/3

**Comment by taprosoft** [comment]
@phv2312 
seem Windows users are more likely to encounter missing git issue because they are more like non-technical users. Let us consider prompt for git windows installation when needed to make it more user friendly.

**Comment by ikunchickchick** [comment]
after downloading,there is a module named decouple failed to be found.
******************************************************
Setting up Miniconda
******************************************************

Conda is installed at C:\Users\admin\Downloads\kotaemon-app\install_dir\conda
Conda version:
conda 24.7.1

******************************************************
Creating conda environment
******************************************************

Conda environment exists at C:\Users\admin\Downloads\kotaemon-app\install_dir\env
Activate conda environment at C:\Users\admin\Downloads\kotaemon-app\install_dir\env

******************************************************
Installing Kotaemon
******************************************************

Dependencies are already installed

******************************************************
Setting up a local model
******************************************************

Traceback (most recent call last):
  File "C:\Users\admin\Downloads\kotaemon-app\scripts\serve_local.py", line 6, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'

**Comment by thefirstLeonliao** [comment]
> after downloading,there is a module named decouple failed to be found.下载后，找不到名为 Decouple 的模块。
> 
> Setting up Miniconda 设置 Miniconda
> 
> Conda is installed at C:\Users\admin\Downloads\kotaemon-app\install_dir\condaConda 安装在 C：\Users\admin\Downloads\kotaemon-app\install_dir\conda Conda version: Conda 版本： conda 24.7.1 康达 24.7.1
> 
> Creating conda environment创建 conda 环境
> 
> Conda environment exists at C:\Users\admin\Downloads\kotaemon-app\install_dir\envConda 环境位于 C：\Users\admin\Downloads\kotaemon-app\install_dir\env Activate conda environment at C:\Users\admin\Downloads\kotaemon-app\install_dir\env在 C：\Users\admin\Downloads\kotaemon-app\install_dir\env 激活 conda 环境
> 
> Installing Kotaemon 安装 Kotaemon
> 
> Dependencies are already installed依赖项已安装
> 
> Setting up a local model设置本地模型
> 
> Traceback (most recent call last):回溯 （最近调用最后）： File "C:\Users\admin\Downloads\kotaemon-app\scripts\serve_local.py", line 6, in 文件“C：\Users\admin\Downloads\kotaemon-app\scripts\serve_local.py”，第 6 行，在 from decouple import config ModuleNotFoundError: No module named 'decouple'ModuleNotFoundError：没有名为“decouple”的模块

same problem，did you solve it？
