### ISSUE TITLE
[BUG] - Cannot upload pdf files because of tenacity.RetryError

### ISSUE THREAD

**Issue by andynady** [Cinnamon/kotaemon#175]
### Description

Having this error when trying to upload any pdf file. Using llama3.1 and able to chat with the model. But file upload shows this error:
File ...\kotaemon-main\install_dir\env\lib\site-packages\tenacity\__init__.py, line 326, in iter raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x235baabbc40 state=finished raised AuthenticationError>]

Tried to troubleshoot with no luck.

### Reproduction steps

```bash
Installed the latest version on 9/1/24
Used admin account to log in
Added llama3.1
Chat works fine
PDF upload:  v9.pdf: RetryError[<Future at 0x235b7316980 state=finished raised AuthenticationError>]
```

### Browsers

Chrome

### OS

Windows

**Comment by taprosoft** [comment]
Likely that you haven't set the embedding model in Index setting to ollama. See https://github.com/Cinnamon/kotaemon/blob/main/docs/local_model.md#use-local-models-for-rag

**Comment by andynady** [comment]
> Likely that you haven't set the embedding model in Index setting to ollama. See https://github.com/Cinnamon/kotaemon/blob/main/docs/local_model.md#use-local-models-for-rag

This helped. Thank you So Much!!!
