### ISSUE TITLE
Files tab visibility

### ISSUE THREAD

**Issue by Rojasundharam** [Cinnamon/kotaemon#177]
### Reference Issues

Restrict Access to the 'Files' Tab to Prevent Unauthorized Viewing and Deletion of Documents"

### Summary

We are uploading our files in the 'Files' tab. Anyone can view and delete these documents, so I need option to hide the 'Files' tab from users.

### Basic Example

Restrict Access to the 'Files' Tab to Prevent Unauthorized Viewing and Deletion of Documents"

### Drawbacks

Any one can delete the documents

### Additional information

![Screenshot (291)](https://github.com/user-attachments/assets/b6952827-8d07-4b35-b534-79dbd4f3c8fb)

**Comment by taprosoft** [comment]
Hi, by default File Collection is public, meaning all users can access and delete the files uploaded to it. You can go to Resources > File Collections > set private: true to restrict access to only owner of that file. 
Alternatively, add a new Collection that is private and your users can upload to both depend on whether on they are planning to share their file with others or not.

**Comment by Rojasundharam** [comment]
The run.windows files is not opening

**Comment by mkhludnev** [comment]
Hello @taprosoft 
Thank you for a great project!
Could elaborate regarding points below?

> You can go to Resources > File Collections > set private: true to restrict access to only owner of that file.

1. one issue is that only admins has Resources  menu, it seems a user can't create private collection for its' own
2. When admin creates a private collection, it isn't not linked to a user, so: everyone can see it, and can upload into. I agree that access control still has place - only those who upload into a private should only see it (beside of #199).

IMHO ideally would be

- assign private collection to a user
- hide it from others
- let users (non-admin) create private collections themselves. 

Does it make sense? How hard to reach those aims?
