### ISSUE TITLE
[BUG] - <title>ModuleNotFoundError: No module named 'ktem'

### ISSUE THREAD

**Issue by Egber1t** [Cinnamon/kotaemon#178]
### Description

import os
import sys

# 获取当前文件所在的目录
current_dir = os.path.dirname(__file__)

# 添加 ktem 模块的路径到 sys.path
sys.path.append(os.path.join(current_dir, 'libs', 'ktem', 'ktem'))

# 从 ktem.main 导入 App
from ktem.main import App  # noqa

# 从 theflow.settings 导入 settings
from theflow.settings import settings as flowsettings

KH_APP_DATA_DIR = getattr(flowsettings, "KH_APP_DATA_DIR", ".")
GRADIO_TEMP_DIR = os.getenv("GRADIO_TEMP_DIR", None)

# 覆盖 GRADIO_TEMP_DIR 如果未设置
if GRADIO_TEMP_DIR is None:
    GRADIO_TEMP_DIR = os.path.join(KH_APP_DATA_DIR, "gradio_tmp")
    os.environ["GRADIO_TEMP_DIR"] = GRADIO_TEMP_DIR

app = App()
demo = app.make()
demo.queue().launch(
    favicon_path=app._favicon,
    inbrowser=True,
    allowed_paths=[
        "libs/ktem/ktem/assets",
        GRADIO_TEMP_DIR,
    ],
)

### Reproduction steps

```bash
I've encountered an issue with “No module named 'ktem'
”.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by cin-albert** [comment]
Hi @Egber1t,

How did you install Kotaemon? From source, docker, or running installers in `scripts`?

If you installed using installers, did you get any errors during the installation, i.e. fail to install dependencies?

**Comment by ataigithub** [comment]
me too idem!!!
“No module named 'ktem'
ktem is used in the application as part of some variable names and also as some folder names, but I haven't found any python module named like that or any python framework module with that name on the internet. Suddenly it starts with a from ktem,main import App, i.e. behaving like a framework that has an App object to export. Please, a reference to this Ktem framework that has such powerful App() objects. Without even being imported. Clarity please, ah... are you using flask?

**Comment by ataigithub** [comment]
according to chatgpt "So far, no popular web framework in Python has a standard app.make() method. This method appears to be specific to a custom library or implementation. If you find app.make() in a script, it is likely a lesser-known or custom library or framework that is not among the most widely used and documented in the Python community."
