### ISSUE TITLE
[REQUEST] - docker run doest do hot reload 

### ISSUE THREAD

**Issue by Niko-La** [Cinnamon/kotaemon#179]
### Summary

Hot reloading is currently not enabled, requiring a rerun of the `docker run` command each time you make changes. Enabling hot reload and providing Docker Compose build instructions would streamline the development process.

### Basic Example

To enable hot reload, configure the Gradio server in `app.py`.

### Drawbacks

_None specified_

**Comment by Niko-La** [comment]
another solution can be to provide docker-compose.yml file and mounting the project folder as volume.  this could allow changes to to the webapp to be reflect via hot reload

**Comment by phv2312** [comment]
Thank @Niko-La for your advice. We will consider adding it. In the mean time you can take a look at this PR https://github.com/Cinnamon/kotaemon/pull/165 which has already provided the docker-compose
