### ISSUE TITLE
The run.windows files is not opening

### ISSUE THREAD

**Issue by Rojasundharam** [Cinnamon/kotaemon#181]
### Description

The run.windows files is not opening

### Reproduction steps

```bash
The run.windows files is not opening
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

**Comment by cin-albert** [comment]
Hi @Rojasundharam,
Have you double-clicked on the `run_windows.bat`? Please clarify the issue you are facing
