### ISSUE TITLE
[REQUEST] - Allow users to upload markdown files

### ISSUE THREAD

**Issue by yacksonn** [Cinnamon/kotaemon#186]
### Summary

Allow users to upload .md files in addition to the existing filetypes.

### Basic Example

Markdown files are pretty popular and there is already handling for .html files so I would assume .md files are not too much more difficult.

### Drawbacks

N/A

**Comment by taprosoft** [comment]
Duplicated https://github.com/Cinnamon/kotaemon/issues/128.
Will be considered in next release.
