### ISSUE TITLE
[BUG] - <Problem in getting anything from the local ollama-llama3.1:8b>

### ISSUE THREAD

**Issue by myildi** [Cinnamon/kotaemon#190]
### Description

Hello, I have chosen the local LLM through ollama, llama3.1:8b. When I check the connection, I get:
"Connection success. Got response: It's nice to meet you. Is there something I can help you with, or would you like to chat?"
I have uploaded some PDF documents. They seem to have been indexed.
But when I ask anything, I get "Error" in the information panel and I get either an empty answer or some unrelated Sub question.
In the terminal window I see the following error:
 File "/Users/myildi/tmp/kotaemon-app/install_dir/env/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x163b69420 state=finished raised AuthenticationError>]

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Safari

### OS

MacOS

**Comment by taprosoft** [comment]
Likely you haven't switch the embedding model in File Collection to `ollama`:
See https://github.com/Cinnamon/kotaemon/blob/main/docs/local_model.md#use-local-models-for-rag

**Comment by myildi** [comment]
> Likely you haven't switch the embedding model in File Collection to `ollama`: See https://github.com/Cinnamon/kotaemon/blob/main/docs/local_model.md#use-local-models-for-rag

Thank you very much! That was very useful!
