### ISSUE TITLE
[BUG] - OperationalError in adding LLM on Hugging Face

### ISSUE THREAD

**Issue by suhanagupta08** [Cinnamon/kotaemon#196]
### Description

Trying to setup and add a new LLM on the Hugging Face interface and facing an error. I have a read-only API key (I previously tried an unrestricted one also and got the same error). Unsure what steps i am missing or doing incorrectly. After going on the link for background on the error it just said it was a common error and related to SQL. I have pasted the error below:

Error
Failed to create LLM openai: Failed to add model openai: (sqlite3.OperationalError) attempt to write a readonly database\n[SQL: UPDATE llm_table SET "default"=?]\n[parameters: (0,)]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)

<img width="1470" alt="Screenshot 2024-09-03 at 1 28 20 PM" src="https://github.com/user-attachments/assets/a3a32c72-9a62-45c8-8885-bc4f3ef75a75">

### Reproduction steps

```bash
1. Go to Hugging Face
2. Click on Add LLM
3. Scroll down to '....'
4. See error
```

### Logs

```bash
Error
Failed to create LLM openai: Failed to add model openai: (sqlite3.OperationalError) attempt to write a readonly database\n[SQL: UPDATE llm_table SET "default"=?]\n[parameters: (0,)]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

### Browsers

Chrome

### OS

MacOS

### Additional information

i have tried a previously active API key and had no change in error.

**Comment by taprosoft** [comment]
HF demo is read-only for archive purpose. Please setup your own key in a local setup of kotaemon. Follow https://cinnamon.github.io/kotaemon/
