### ISSUE TITLE
[BUG] - Download All files from private collections

### ISSUE THREAD

**Issue by mkhludnev** [Cinnamon/kotaemon#199]
### Description

Private collection hides files from non-owner, but I'm able to download files including hidden ones. 

followup #177

### Reproduction steps

```bash
1. Crete private collection
2. Upload file into private collection
3. Logout, login another user (non-admin)
4. Go to Files, select that private collection
5. There is no files visible since collection is private 1. and user has been changed 4.
6. Click Download all files 

# Expect
No files, or error, or unable to click

# Actual 
Got all files in archive
```

### Screenshots

![Screenshot from 2024-09-03 13-27-56](https://github.com/user-attachments/assets/4d65696c-d840-4c62-a667-63301b70322a)

### Browsers

Firefox

### OS

Linux

**Comment by mkhludnev** [comment]
If you confirm it I would like to come up with PR.

**Comment by taprosoft** [comment]
Confirm this is unwanted behavior.

**Comment by mkhludnev** [comment]
The fix disabled dowloadAll for private collection. Fair. I'll try to request download a file which a user has no access.
