### ISSUE TITLE
[REQUEST] - add light/dark mode toggle button to webapp header

### ISSUE THREAD

**Issue by Niko-La** [Cinnamon/kotaemon#207]
### Summary

current default is dark mode. while professional users perfer light mode.  currently not that intutitve to set default mode or change using ui

### Basic Example

.

### Drawbacks

.

**Comment by taprosoft** [comment]
![image](https://github.com/user-attachments/assets/78dbb7ff-8ec6-4b29-a6e2-ad1bb1e347ae)
Is this toggle suffice your need? We plan to make it more visible to user but for now you can use this.

**Comment by Niko-La** [comment]
@taprosoft  yes easy for me but my coworkers are nontechies and it defaults to dark always.  but i suppose i can support them by setting it up for them with login

**Comment by taprosoft** [comment]
Yes we will include this in our back-log.
