### ISSUE TITLE
How to set the graphRAG with local ollama

### ISSUE THREAD

**Issue by edenbuaa** [Cinnamon/kotaemon#212]
### Description

How to set the graphRAG with local ollama?

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by mkhludnev** [comment]
I briefly look through code noticed explicit reference to OpenAI eg https://github.com/Cinnamon/kotaemon/blob/8be8a4a9d048d551aaf79b98e235ea41ec94b695/libs/ktem/ktem/index/file/graph/pipelines.py#L232, it might not be ready for local llms

**Comment by mkhludnev** [comment]
Another issue is that graphrag is a separate program with own configuration. Which could be configured to other llm but it's a separate question https://github.com/microsoft/graphrag/issues/657

**Comment by mkhludnev** [comment]
> I briefly look through code noticed explicit reference to OpenAI eg
> 
> https://github.com/Cinnamon/kotaemon/blob/8be8a4a9d048d551aaf79b98e235ea41ec94b695/libs/ktem/ktem/index/file/graph/pipelines.py#L232
> , it might not be ready for local llms

I stuck here 

```
Entity count: 318
2024-09-09 19:15:38.962 - openai._base_client/DEBUG - Sending HTTP Request: POST https://api.openai.com/v1/embeddings

Error embedding chunk {'OpenAIEmbedding': "Error code: 
```
I think it should pick default configured embeddings instead.

**Comment by edenbuaa** [comment]
@mkhludnev thanks.  I can build the graphRAG and run the pipeline successfully with my local ollama after a investigation about graphrag component.

But I got error which point to the mismatch of embedding between openai and ollama during the query stage. This error is hidden in the kotaemon pipeline, seems a lot of work to fix it.

**Comment by kksasa** [comment]
if someone can run ollama for graphrag. Please share the steps to us :）

**Comment by edenbuaa** [comment]
Finally, it works. I will make a PR to this repo

**Comment by MortalHappiness** [comment]
@kksasa You can try my Gist here: https://gist.github.com/MortalHappiness/7030bbe96c4bece8a07ea9057ba18b86

**Comment by taprosoft** [comment]
Please check the latest version and instruction for setting up GraphRAG here https://github.com/Cinnamon/kotaemon#setup-graphrag.
