### ISSUE TITLE
[BUG] - <title> Unable to log in

### ISSUE THREAD

**Issue by topoadmin** [Cinnamon/kotaemon#213]
### Description

Do not display login window
![image](https://github.com/user-attachments/assets/9100c426-c0ba-4df8-ab5c-195774abcbcb)
![image](https://github.com/user-attachments/assets/f77c5229-444e-408e-bedb-2dbe121dc54e)

### Reproduction steps

```bash
# file .env
LOCAL_MODEL=llama3.1:8b-instruct-q8_0
LOCAL_MODEL_EMBEDDINGS=nomic-embed-text
```

### Browsers

Chrome

### OS

Windows

**Comment by phv2312** [comment]
Have you try the 1st URL: `127.0.0.1:7860` ?

**Comment by topoadmin** [comment]
> Have you try the 1st URL: `127.0.0.1:7860` ?

Yes, it's the same.

**Comment by taprosoft** [comment]
@topoadmin access through Gradio live URL feature is not well-tested and can produce some weird issues with Javascript loading (which is required for log in). Please wait while we are verifying this issue.

Meanwhile, please try local URL or port-forwarding first (if you know how to use SSH).

**Comment by vap0rtranz** [comment]
I also see this login prompt after a new install.

How to disable this?  I see something about user management extensions in the website docs.

![kotaemon](https://github.com/user-attachments/assets/12f7e3e8-cb02-4d68-b86a-4e32e2b366a9)

**Comment by vap0rtranz** [comment]
Nevermind ^.  I found the username/password in the dev guide.  https://cinnamon.github.io/kotaemon/development/

**Comment by HanyinWang** [comment]
Is this solved? I have the same issue.

![Screenshot 2024-09-06 at 4 41 17 PM](https://github.com/user-attachments/assets/3e19e921-294f-4889-8f43-8e1568610f1c)

**Comment by pathros** [comment]
How do I login when using Docker?
```zsh
docker run \
-e GRADIO_SERVER_NAME=0.0.0.0 \
-e GRADIO_SERVER_PORT=7860 \
-p 7860:7860 \
-d \
--platform linux/arm64 \
ghcr.io/cinnamon/kotaemon:main-lite

```
Then, when I access `http://localhost:7860` the first thing I see is a login form. What is then the default username and password? For this docker case, how do I set up that login information or how do I register?

**UPDATE**
Well, from detached mode I could see the following info:
```zsh
User "admin" created successfully
Setting up quick upload event
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
User-id: None, can see public conversations: False
User-id: None, can see public conversations: False
User-id: None, can see public conversations: False
```
then I tried `admin`in both login form fields and it worked.
