### ISSUE TITLE
[BUG] - Missing create_final_nodes.parquet in Graphrag Workflow Execution

### ISSUE THREAD

**Issue by gogodechen1** [Cinnamon/kotaemon#214]
### Description

I am working with the Graphrag system and encountered an issue where the create_final_nodes.parquet file is not being generated during the workflow execution. The process for create_base_text_units.parquet is successful, but the pipeline fails when it reaches the create_final_nodes step, citing a missing file error，or I miss something？

### Reproduction steps

```bash
Go to the Graphrag project folder.
Set up a CSV file for indexing.
Execute the pipeline with the default workflows, including the create_base_text_units, create_base_entity_graph, and create_final_nodes.
The pipeline successfully creates the create_base_text_units.parquet, but fails to create the create_final_nodes.parquet with a FileNotFoundError.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\kotaemon-app\\ktem_app_data\\user_data\\files\\graphrag\\output\\create_final_nodes.parquet'

16:30:55,553 graphrag.index.cli INFO Logging enabled at F:\kotaemon-app\ktem_app_data\user_data\files\graphrag\output\20240904-163055\reports\indexing-engine.log
...
16:30:55,857 graphrag.index.emit.parquet_table_emitter INFO emitting parquet table create_base_text_units.parquet
```

### OS

Windows

### Additional information

Embeddings and LLM models are configured correctly in GraphRagConfig.
No relevant workflows were skipped in the configuration.
The process was run using the default pipeline configuration, with all dependencies installed as required.

**Comment by MikeEchoVoid** [comment]
hi, same bug. Is there anything I can do  ?

**Comment by eyangs** [comment]
same bug

**Comment by Lee-Ju-Yeong** [comment]
same bug

**Comment by vip-china** [comment]
Has anyone solved it?
![image](https://github.com/user-attachments/assets/04c9df59-5f15-4e14-bb7a-09573a16be12)

**Comment by CASlee02** [comment]
`    def _build_graph_search(self):
            assert (
                len(self.file_ids) <= 1
            ), "GraphRAG retriever only supports one file_id at a time"
    
            file_id = self.file_ids[0]
            # retrieve the graph_id from the index
            with Session(engine) as session:
                graph_id = (
                    session.query(self.Index.target_id)
                    .filter(self.Index.source_id == file_id)
                    .filter(self.Index.relation_type == "graph")
                    .first()
                )
                graph_id = graph_id[0] if graph_id else None
                assert graph_id, f"GraphRAG index not found for file_id: {file_id}"
    
            root_path, _ = prepare_graph_index_path(graph_id)
            output_path = root_path / "output"
            child_paths = sorted(
                list(output_path.iterdir()), key=lambda x: x.stem, reverse=True
            )
            print(f"Child paths: {child_paths}")
    
            # get the latest child path
            assert child_paths, "GraphRAG index output not found"
            latest_child_path = Path(child_paths[0]) / "artifacts"
            print(f"Latest child path: {latest_child_path}")
    
            INPUT_DIR = latest_child_path
            OUTPUT_DIR = output_path # No longer need to path to artifacts as it no longer exists in the directory path for GraphRAG
            LANCEDB_URI = str(OUTPUT_DIR / "lancedb")
            COMMUNITY_REPORT_TABLE = "create_final_community_reports"
            ENTITY_TABLE = "create_final_nodes"
            ENTITY_EMBEDDING_TABLE = "create_final_entities"
            RELATIONSHIP_TABLE = "create_final_relationships"
            TEXT_UNIT_TABLE = "create_final_text_units"
            COMMUNITY_LEVEL = 2
    
            # read nodes table to get community and degree data
            entity_df = pd.read_parquet(f"{OUTPUT_DIR}/{ENTITY_TABLE}.parquet")
            print(f"{OUTPUT_DIR}/{ENTITY_TABLE}.parquet")
            entity_embedding_df = pd.read_parquet(
                f"{OUTPUT_DIR}/{ENTITY_EMBEDDING_TABLE}.parquet"
            )
            entities = read_indexer_entities(
                entity_df, entity_embedding_df, COMMUNITY_LEVEL
            )
    
            # load description embeddings to an in-memory lancedb vectorstore
            # to connect to a remote db, specify url and port values.
            description_embedding_store = LanceDBVectorStore(
                collection_name="entity_description_embeddings",
            )
            description_embedding_store.connect(db_uri=LANCEDB_URI)
            if Path(LANCEDB_URI).is_dir():
                rmtree(LANCEDB_URI)
            _ = store_entity_semantic_embeddings(
                entities=entities, vectorstore=description_embedding_store
            )
            print(f"Entity count: {len(entity_df)}")
    
            # Read relationships
            relationship_df = pd.read_parquet(f"{OUTPUT_DIR}/{RELATIONSHIP_TABLE}.parquet")
            relationships = read_indexer_relationships(relationship_df)
    
            # Read community reports
            report_df = pd.read_parquet(f"{OUTPUT_DIR}/{COMMUNITY_REPORT_TABLE}.parquet")
            reports = read_indexer_reports(report_df, entity_df, COMMUNITY_LEVEL)
    
            # Read text units
            text_unit_df = pd.read_parquet(f"{OUTPUT_DIR}/{TEXT_UNIT_TABLE}.parquet")
            text_units = read_indexer_text_units(text_unit_df)
    
            embedding_model = os.getenv("GRAPHRAG_EMBEDDING_MODEL")
            # Patch here
            graph_api_url, graph_embedding_api_url = os.getenv("GRAPHRAG_API_BASE"), os.getenv("GRAPHRAG_EMBEDDING_API_BASE")
            if graph_embedding_api_url is not None:
                graph_api_url = graph_embedding_api_url
            text_embedder = OpenAIEmbedding(
                api_key=os.getenv("OPENAI_API_KEY"),
                api_base=graph_api_url,  #api_base=None, 
                api_type=OpenaiApiType.OpenAI,
                model=embedding_model,
                deployment_name=embedding_model,
                max_retries=20,
            )
            # Patch done
            token_encoder = tiktoken.get_encoding("cl100k_base")
    
            context_builder = LocalSearchMixedContext(
                community_reports=reports,
                text_units=text_units,
                entities=entities,
                relationships=relationships,
                covariates=None,
                entity_text_embeddings=description_embedding_store,
                embedding_vectorstore_key=EntityVectorStoreKey.ID,
                # if the vectorstore uses entity title as ids,
                # set this to EntityVectorStoreKey.TITLE
                text_embedder=text_embedder,
                token_encoder=token_encoder,
            )
            return context_builder`
        
I managed to get mine working by replacing the output directory for the GraphRAG parquets to the output_path instead of the latest_child_path. For some reason GraphRAG no longer creates a separate artifacts directory. The changes are contained in this function "_build_graph_search(self)" within the libs/ktem/ktem/index/file/graph/pipelines.py

**Comment by ZSTank** [comment]
I have the same problem, and I still don't know how to solve it
![bug-1](https://github.com/user-attachments/assets/73652fa1-3fd3-4c0a-92c7-df04a9b812d3)

**Comment by vip-china** [comment]
> 我有同样的问题，但我仍然不知道如何解决它 ![错误 1](https://private-user-images.githubusercontent.com/86126695/376003770-73652fa1-3fd3-4c0a-92c7-df04a9b812d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NzA2NDYsIm5iZiI6MTcyODg3MDM0NiwicGF0aCI6Ii84NjEyNjY5NS8zNzYwMDM3NzAtNzM2NTJmYTEtM2ZkMy00YzBhLTkyYzctZGYwNGE5YjgxMmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAxNDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3N2ZkYmY0Y2M3YTFiMjNhMGNhN2M4YTFmMGI3NmMwOGM1YjRhZDFkMWI5MTY5Nzk2YTU1NzIxODI1NGY3NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0tjC7tGHUIAeQDHeRuze86Llo3r49GglyhFI0UZ58NE)

Has the latest code been updated? Updating the latest code should solve the problem. If it has been updated, please check if the GRAPHRAG index is complete

**Comment by taprosoft** [comment]
Please check the latest version and instruction for setting up GraphRAG here https://github.com/Cinnamon/kotaemon#setup-graphrag.

**Comment by ChristopheZhao** [comment]
I encountered the same problem, and I installed the latest version of GraphRAG following https://github.com/Cinnamon/kotaemon#setup-graphrag, but the problem still persists. Has anyone solved it yet?

**Comment by sunnf8888** [comment]
我也是一直是这个问题，按照官网来部署ollama模型服务，别的都可以，就是一直这个错误
Retrievers [DocumentRetrievalPipeline(DS=<kotaemon.storages.docstores.lancedb.LanceDBDocumentStore object at 0x7fca63e2a5c0>, FSPath=PosixPath('/root/autodl-tmp/kotaemon/ktem_app_data/user_data/files/index_1'), Index=<class 'ktem.index.file.index.IndexTable'>, Source=<class 'ktem.index.file.index.Source'>, VS=<kotaemon.storages.vectorstores.chroma.ChromaVectorStore object at 0x7fca63e2a9e0>, get_extra_table=False, llm_scorer=LLMTrulensScoring(concurrent=True, normalize=10, prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7fca63b65090>, system_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7fca63b651b0>, top_k=3, user_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7fca63b65300>), mmr=False, rerankers=[CohereReranking(cohere_api_key='', model_name='rerank-multilingual-v2.0')], retrieval_mode='hybrid', top_k=10, user_id=1), GraphRAGRetrieverPipeline(DS=<theflow.base.unset_ object at 0x7fcb22d82f20>, FSPath=<theflow.base.unset_ object at 0x7fcb22d82f20>, Index=<class 'ktem.index.file.index.IndexTable'>, Source=<theflow.base.unset_ object at 0x7fcb22d82f20>, VS=<theflow.base.unset_ object at 0x7fcb22d82f20>, file_ids=['72c5f060-3048-40e4-b7ea-783033c5befd'], user_id=<theflow.base.unset_ object at 0x7fcb22d82f20>)]
searching in doc_ids []
Traceback (most recent call last):
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/gradio/queueing.py", line 575, in process_events
    response = await route_utils.call_process_api(
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/gradio/utils.py", line 663, in async_iteration
    return await iterator.__anext__()
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/gradio/utils.py", line 656, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/gradio/utils.py", line 639, in run_sync_iterator_async
    return next(iterator)
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/gradio/utils.py", line 801, in gen_wrapper
    response = next(iterator)
  File "/root/autodl-tmp/kotaemon/libs/ktem/ktem/pages/chat/__init__.py", line 876, in chat_fn
    for response in pipeline.stream(chat_input, conversation_id, chat_history):
  File "/root/autodl-tmp/kotaemon/libs/ktem/ktem/reasoning/simple.py", line 655, in stream
    docs, infos = self.retrieve(message, history)
  File "/root/autodl-tmp/kotaemon/libs/ktem/ktem/reasoning/simple.py", line 483, in retrieve
    retriever_docs = retriever_node(text=query)
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/theflow/base.py", line 1097, in __call__
    raise e from None
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/theflow/base.py", line 1088, in __call__
    output = self.fl.exec(func, args, kwargs)
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/theflow/backends/base.py", line 151, in exec
    return run(*args, **kwargs)
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/theflow/middleware.py", line 144, in __call__
    raise e from None
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/theflow/middleware.py", line 141, in __call__
    _output = self.next_call(*args, **kwargs)
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/theflow/middleware.py", line 117, in __call__
    return self.next_call(*args, **kwargs)
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/theflow/base.py", line 1017, in _runx
    return self.run(*args, **kwargs)
  File "/root/autodl-tmp/kotaemon/libs/ktem/ktem/index/file/graph/pipelines.py", line 419, in run
    context_builder = self._build_graph_search()
  File "/root/autodl-tmp/kotaemon/libs/ktem/ktem/index/file/graph/pipelines.py", line 294, in _build_graph_search
    entity_df = pd.read_parquet(f"{INPUT_DIR}/{ENTITY_TABLE}.parquet")
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/pandas/io/parquet.py", line 667, in read_parquet
    return impl.read(
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/pandas/io/parquet.py", line 267, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/pandas/io/parquet.py", line 140, in _get_path_or_handle
    handles = get_handle(
  File "/root/autodl-tmp/conda-envs/kotaemon/lib/python3.10/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/kotaemon/ktem_app_data/user_data/files/graphrag/b22c9f81-40a1-416d-b10a-4a683a797e45/output/create_final_nodes.parquet'

**Comment by sunnf8888** [comment]
我也有相同的的错误,0.7.1 的版本

**Comment by lonngxiang** [comment]
same
![image](https://github.com/user-attachments/assets/984b40d1-c95e-4265-9bc3-527d2ae37816)

**Comment by duongkstn** [comment]
any updates ? the error is still there !

**Comment by FHhui** [comment]
OMG!!!this error is still here

**Comment by duongkstn** [comment]
Hi, in my case, I think the problem is time. yes, I have to wait another 10 mins to have that file . In the UI, it said that the indexing process is completed. But in folder, you guys have to wait 10 mins.

I do not know why, may be due to multiprocessing mechanism of kotaemon.
