### ISSUE TITLE
[REQUEST] - Question about private collection

### ISSUE THREAD

**Issue by mkhludnev** [Cinnamon/kotaemon#215]
### Reference Issues

#177 follow-up

### Summary

@taprosoft 

> You can go to Resources > File Collections > set private: true to restrict access to only owner of that file.

One issue is that only admins has Resources menu, it seems a user can't create private collection for its' own.
When admin creates a private collection, it isn't not linked to a user, so: everyone can see it, and can upload into. I agree that access control still has place - only those who upload into a private should only see it.

IMHO ideally would be

- assign private collection to a user
- hide it from others
- let users (non-admin) create private collections themselves. (Is it blocked by necessity of restating app after creating collection?)

Does it make sense? How hard to reach those aims?

### Basic Example

There's a private collection assigned to someone, what others can't see this collection.

### Drawbacks

Maybe it's too hard.

**Comment by taprosoft** [comment]
>assign private collection to a user
hide it from others
let users (non-admin) create private collections themselves. (Is it blocked by necessity of restating app after creating collection?)

Thanks for the suggestion. Indeed this use case is valid from our perspective. We are working on a "lite" collection feature called `file group`, which help users to define their own custom set of files and perform QA on it, or, combine any `file group` with individual files.

Let me know if it fit your request @mkhludnev.

**Comment by mkhludnev** [comment]
> We are working on a "lite" collection feature called `file group`

It sounds like a right direction toward. But it's not obvious why to introduce a new entity. I don't know, but maybe it's related to limitations of existing collections - I noticed `required reboot` message. I already described how it seems to me, but you definitely have a vision and can choose a better approach. 
Thanks for the great project!

**Comment by mkhludnev** [comment]
moving to https://github.com/Cinnamon/kotaemon/discussions/241
