### ISSUE TITLE
[REQUEST] - Integrate another GraphRAG backend

### ISSUE THREAD

**Issue by gusye1234** [Cinnamon/kotaemon#243]
### Summary

I'm wondering, do the core dev team consider integrating another GraphRAG? 
I'm the author of the [`nano-graphrag`](https://github.com/gusye1234/nano-graphrag). `nano-graphrag` uses much less code to implement nearly the same functionality of the official GraphRAG and requires much more less deps. It supports extensions like ollama, faiss, milvus and more pythonic and portable.  
If the core dev is open to integrate another GraphRAG backend, I hope I can push a PR about integrating `nano-graphrag`.
Looking forward to the response!

### Basic Example

Add a pipeline like the GraphRAG in here: `libs/ktem/ktem/index/file/graph/pipelines.py`

### Drawbacks

Maybe affect the indexing performance in some ways, since `nano-graphrag` is not exactly the same as the official one

**Comment by taprosoft** [comment]
@gusye1234 sorry for our late response. I briefly check the `nano-graphrag` implementation and it looks great! Planning to do this ourselves but we are glad if you can help us :D

**Comment by gusye1234** [comment]
Cool, let me know if anything I could help❤️.

**Comment by taprosoft** [comment]
https://github.com/Cinnamon/kotaemon/releases/tag/v0.7.4
