### ISSUE TITLE
[REQUEST] - Can graphrag support other free LLMs like qwen2?

### ISSUE THREAD

**Issue by llkdd1** [Cinnamon/kotaemon#245]
### Summary

support other free LLMs like qwen2

### Basic Example

support other free LLMs like qwen2

### Drawbacks

support other free LLMs like qwen2

**Comment by taprosoft** [comment]
Please check the latest version and instruction for setting up GraphRAG here https://github.com/Cinnamon/kotaemon#setup-graphrag.
