### ISSUE TITLE
[BUG] - <title>class `CohereEmbeddings` was deprecated in LangChain 0.0.30

### ISSUE THREAD

**Issue by wingchiu** [Cinnamon/kotaemon#247]
### Description

The class `CohereEmbeddings` was deprecated in LangChain 0.0.30 and will be removed in 0.3.0. An updated version of the class exists in the langchain-cohere package and should be used instead. To use it run `pip install -U langchain-cohere` and import as `from langchain_cohere import CohereEmbeddings`.

GraphRAG dependencies not installed. GraphRAG retriever pipeline will not work properly.
User "admin" already exists
Setting up quick upload event
Running on local URL:  http://127.0.0.1:7860

Not sure what's wrong with the CoehereEmeddings depreciation? What's the correct model to install?

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by taprosoft** [comment]
Hi, this is just a deprecation warning and won't affect Kotaemon functionality. Feel free to raise issue if you have problem using Cohere API for embedding.
