### ISSUE TITLE
Failed to upload and index the file, retried multiple times

### ISSUE THREAD

**Issue by cin-jimmy** [Cinnamon/kotaemon#25]
![image](https://github.com/Cinnamon/kotaemon/assets/54021405/9de42d66-8fe7-4e66-ae2d-60f149363df8)

**Comment by cin-jimmy** [comment]
![image](https://github.com/Cinnamon/kotaemon/assets/54021405/b7436f75-c9de-434a-8f02-7e05b27df154)

**Comment by trducng** [comment]
@cin-jimmy I wonder if you have the errors relating to fastembed installation?

**Comment by lone17** [comment]
> @cin-jimmy I wonder if you have the errors relating to fastembed installation?

@trducng perhaps you should ask this on our slack channel as he might not be active on github.

**Comment by cin-jimmy** [comment]
| fastembed installation

Not sure if I did that. Simply followed the instruction and click-installing all the windows files.

**Comment by cin-jimmy** [comment]
This issue has been resolved @trducng , @lone17
