### ISSUE TITLE
[BUG] - <title>GraphRag default modle is GPT-4-TURBO

### ISSUE THREAD

**Issue by bookandlover** [Cinnamon/kotaemon#250]
### Description

When I upload a new text file to create a Graphrag index, the default model in the settings.yaml file is gtp-4-turbo, which is very expensive. How do I change the model to gpt-4o-mini?

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

MacOS

**Comment by ihoment-lys** [comment]
Is there a solution?

**Comment by taprosoft** [comment]
Please check the latest version and instruction for setting up GraphRAG here https://github.com/Cinnamon/kotaemon#setup-graphrag.
