### ISSUE TITLE
[BUG] - <title> Do not know how to sign in (User- Password) 

### ISSUE THREAD

**Issue by TuHocAI** [Cinnamon/kotaemon#253]
### Description

After install with Terminal on Mac OS, a browser is opened (screenshot below). But I can not have User and Password to sign in, also how to sign up. Please help. 

### Reproduction steps

```bash
I can not use the Koatemon because of not having User and password.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
https://drive.google.com/file/d/19X0gJtA4TIWWkE8xMZQ9auKCGoGAiMRB/view?usp=sharing
```

### Browsers

Chrome

### OS

MacOS

**Comment by WeipengMO** [comment]
Default username / password are: admin / admin. You can setup additional users directly on the UI.

https://cinnamon.github.io/kotaemon/development/

**Comment by khankaholic** [comment]
Thanks @WeipengMO for your comment.
