### ISSUE TITLE
Unable to find image

### ISSUE THREAD

**Issue by ihoment-lys** [Cinnamon/kotaemon#258]
### Description

ghcr.io/cinnamon/kotaemon:latest
Unable to find image 'ghcr.io/cinnamon/kotaemon:latest' locally
latest: Pulling from cinnamon/kotaemon
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
ghcr.io/cinnamon/kotaemon:latest
Unable to find image 'ghcr.io/cinnamon/kotaemon:latest' locally
latest: Pulling from cinnamon/kotaemon
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
```

### OS

MacOS

**Comment by phv2312** [comment]
It seems like you're using Mac with chip M.
Currently we don't have the pre-built docker image for platform arm64 on github container registry yet. But we are working on this platform soon.
The closest solution may be change the dockerfile (add cargo) and build the docker manually. Here is the PR https://github.com/Cinnamon/kotaemon/pull/226
