### ISSUE TITLE
[BUG] - <title>Error: 'gbk' codec can't encode character

### ISSUE THREAD

**Issue by kksasa** [Cinnamon/kotaemon#263]
### Description

The ms graphrag index is so hard to use? Upload several pdf both cannot be parsed with below error
Error: 'gbk' codec can't encode character '\xa9' in position 238: illegal multibyte sequence

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

**Comment by smilefufu** [comment]
Same error here. This is what I'm trying to upload.
[car-kn1.md](https://github.com/user-attachments/files/16959937/car-kn1.md)

I think my doc encoding is utf-8, why gbk is used?

I deployed without docker on my win11 PC.

**Comment by RealmX1** [comment]
same question. How can we change encoding method used?
