### ISSUE TITLE
[REQUEST] - <title>WHY GraphRAG retriever only supports one file_id at a time 

### ISSUE THREAD

**Issue by Shihui628** [Cinnamon/kotaemon#269]
### Summary

can more graph rag file_ids be supported in future versions?  I want to leverage the advantages of GraphRAG in the multi-document Query-Focused Summarization (QFS) problem.

### Basic Example

Cross-document indexing search

### Drawbacks

no

**Comment by kksasa** [comment]
marked it for the answer

**Comment by taprosoft** [comment]
HI, actually it is just how the current indexing process work for GraphRAG. You can upload multiple files at the same times (make sure that you press `Upload and Index` once).
Later just select any one of those uploaded files and retrieval process will consider all files uploaded together in that session.

But, if you want to gradually upload files one-by-one, then perform query on the whole collection it is not supported at the moment. Still some small changes in the code can support this quite easily.
