### ISSUE TITLE
[BUG] -run_macos.sh error

### ISSUE THREAD

**Issue by pxh520** [Cinnamon/kotaemon#276]
### Description

Traceback (most recent call last):
  File "/Users/work/Downloads/kotaemon-app/scripts/serve_local.py", line 6, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'

******************************************************
Launching Kotaemon in your browser, please wait...
******************************************************

Traceback (most recent call last):
  File "/Users/work/Downloads/kotaemon-app/app.py", line 3, in <module>
    from theflow.settings import settings as flowsettings
ModuleNotFoundError: No module named 'theflow'

Will exit now...

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Safari

### OS

MacOS

**Comment by taprosoft** [comment]
One possible cause is that your machine lack of Git command. Can you check and follow this: https://git-scm.com/download/mac

**Comment by taprosoft** [comment]
Also please provide terminal output of `run_macos.sh` so we can diagnose more.
