### ISSUE TITLE
Ollama Graph Embedding Fails in Local LLM Setup

### ISSUE THREAD

**Issue by Niko-La** [Cinnamon/kotaemon#283]
### Description

# Ollama Graph Embedding Fails in Local LLM Setup

## Summary
The graph embedding process using local Ollama LLM is failing during the GraphRAG indexing step, specifically at the `create_base_entity_graph` stage.

## Error
```
❌ create_base_entity_graph
None
```

## Steps to Reproduce
1. Initiate GraphRAG indexing process on a PDF document
2. Observe the process fail at the `create_base_entity_graph` stage

## Current Behavior
- The indexing process completes the following steps:
  - `create_base_text_units`
  - `create_base_extracted_entities`
  - `create_summarized_entities`
- It fails at `create_base_entity_graph` with no error message, just returning `None`

## Expected Behavior
The `create_base_entity_graph` step should complete successfully, creating the entity graph for the indexed document.

## Possible Causes
1. Ollama LLM configuration issue for graph embedding
2. Incompatibility between Ollama and the graph embedding process
3. Resource constraints or timeout during the graph creation process

## Next Steps
1. Review Ollama LLM configuration for graph embedding tasks
2. Check logs for any hidden error messages or warnings
3. Verify Ollama's compatibility with the current graph embedding implementation
4. Test the graph embedding process with smaller documents to isolate potential resource issues
5. Implement more detailed error logging in the `create_base_entity_graph` function

## Impact
This issue is blocking the creation of entity graphs, which is crucial for advanced RAG capabilities. Resolving this will enhance our local LLM's ability to perform complex document analysis and retrieval tasks.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by enoche** [comment]
Marked to follow: error on `no file found at  embed output`

**Comment by LittleNightmare** [comment]
i meet same problem. i just check the log of graph rag, it still looks like it's trying to connect to openai. and i have set related settings to ollama

i am using docker version 

PS: i try clone it but suffer import issue, which always missing html2text (it is exist in my env)

**Comment by taprosoft** [comment]
Please check the latest version and instruction for setting up GraphRAG here https://github.com/Cinnamon/kotaemon#setup-graphrag.
