### ISSUE TITLE
[BUG] - Test indexing retrieval test does not pass

### ISSUE THREAD

**Issue by bfdykstra** [Cinnamon/kotaemon#292]
### Description

`pytest -s libs/kotaemon/tests/test_indexing_retrieval.py`

fails with `KeyError: 'file_name'` because there is no metadata created with the files

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by phv2312** [comment]
Thanks for your report @bfdykstra . The dummy example in the pytest doesn't contain the required metadata fields (`file_name`) while almost real Document variable should have.
