### ISSUE TITLE
[REQUEST] - docling

### ISSUE THREAD

**Issue by thistleknot** [Cinnamon/kotaemon#294]
### Summary

docling supports automatic parsing of pdf's with tables.  I've found it very beneficial.
https://github.com/DS4SD/docling/issues

### Basic Example

automatic table extraction

### Drawbacks

gpu access
changes format of incoming document, but I've found it much easier to read pdfs processed by markdown.  Uses layout detection + vision transformers to translate tables to markdown representations

**Comment by cin-albert** [comment]
Thanks for the request. I'm working on it and will add it to the readers soon
