### ISSUE TITLE
[REQUEST] - User Data Persistence whit Docker

### ISSUE THREAD

**Issue by architectonio** [Cinnamon/kotaemon#297]
### Reference Issues

No Persistence of User Data (Created Users or uploaded Documents) when removing and recreating the docker container.

### Summary

I am running Tests with Kotaemon, which I find really complete and a step ahead of other solutions found on GitHub. I do the tests using Docker, specifically the main-full image.
When I remove the container and create a new one (new image) I could not maintain both the persistence of the user data (documents) and the users created. 

I created a volume that I called "**kotaemon-data**" then I create/start the container with this command: 
**docker run  -e GRADIO_SERVER_NAME=0.0.0.0 -e GRADIO_SERVER_PORT=7860 -p 7860:7860 -v kotaemon-data:/ktem_app_data --restart always --name="kotaemon" -it  ghcr.io/cinnamon/kotaemon:main-full**
Everything seems to run but there is no persistence of data and looking in the created volume it is empty (only a **/_data** directory is in there).

Is there any way to get the persistency?
Thanks in advance

### Basic Example

docker run  -e GRADIO_SERVER_NAME=0.0.0.0 -e GRADIO_SERVER_PORT=7860 -p 7860:7860 **-v kotaemon-data:/ktem_app_data** --restart always --name="kotaemon" -it  ghcr.io/cinnamon/kotaemon:main-full

### Drawbacks

No persistence of user data

**Comment by phv2312** [comment]
Hmm, my quick check seems that the folder which you mount inside Docker is not the correct ones.
Can you try:
`... -v kotaemon-data:/app/ktem_app_data ...`

**Comment by architectonio** [comment]
I partially got it: ....**kotaemon-data:/app/ktem_app_data/user_data/**....   document and indexes are persistent. 
However no _kotaemon configuration_ is preserved and the same is for the users i have created.
Now I am going to proceed as suggested by you.
Thank you

**Comment by architectonio** [comment]
@phv2312 
It works!
Thanks a lot for your support!
