### ISSUE TITLE
[BUG] - <title>docker run error

### ISSUE THREAD

**Issue by stormsea** [Cinnamon/kotaemon#305]
### Description

run
```
docker run \
-e GRADIO_SERVER_NAME=0.0.0.0 \
-e GRADIO_SERVER_PORT=7860 \
-p 7860:7860 -d --rm \
--name kotaemon \
ghcr.io/cinnamon/kotaemon:main-full
```

docker logs show
```
[nltk_data] Error loading punkt_tab: <urlopen error [Errno 99] Cannot
[nltk_data]     assign requested address>
/usr/local/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:119: LangChainDeprecationWarning:

The class `CohereEmbeddings` was deprecated in LangChain 0.0.30 and will be removed in 0.3.0. An updated version of the class exists in the langchain-cohere package and should be used instead. To use it run `pip install -U langchain-cohere` and import as `from langchain_cohere import CohereEmbeddings`.
```

It seems that there was a network error while downloading NLTK. Could you please download all the files during the Docker build phase?

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by cyshi** [comment]
I encountered the same problem

**Comment by jacmule** [comment]
It seems like the lastest image(main-full) also has this question.

**Comment by taprosoft** [comment]
@stormsea @jacmule thanks for the report. We will move NLTK download to Docker build script in next release. Meanwhile can you try to start the Docker image with an active Internet connection a few time so it can complete the initialization step?

**Comment by jacmule** [comment]
> [@stormsea](https://github.com/stormsea) [@jacmule](https://github.com/jacmule) thanks for the report. We will move NLTK download to Docker build script in next release. Meanwhile can you try to start the Docker image with an active Internet connection a few time so it can complete the initialization step?

Thanks for your reply.In fact, I need to deploy it in a strictly controlled network environment, so I really want to ensure that once the container is up, all necessary dependencies are already in place without requiring additional downloads.
