### ISSUE TITLE
[REQUEST] - <title> Each user being able to set chunk size and overlap for indices.

### ISSUE THREAD

**Issue by LucianoSP** [Cinnamon/kotaemon#308]
### Reference Issues

290

### Summary

Each user able to set chunk size and overlap for indices.

### Basic Example

Im also confused about how to set chunk size and overlap. This should be something that each user can modify if they want. This changes with each user case and data type. 
Is it possible to configure this from this page?
![image](https://github.com/user-attachments/assets/f741d584-05fd-4282-bc93-df9239cbd014)

Changing the flowsettings.py and having to compose a new image in docker everytime I want to test different settings?
Please help me find a solution for this awesome project so I can put it in production. 
Thanks in advance.

### Drawbacks

none I can see.

**Comment by LucianoSP** [comment]
no comments?

**Comment by taprosoft** [comment]
@LucianoSP this is a valid concern. We are working on this in our backlog. Sorry for the late reply.
