### ISSUE TITLE
[BUG] - <title>How can I sign up? 

### ISSUE THREAD

**Issue by yusufdurmus** [Cinnamon/kotaemon#315]
### Description

I installed the app and got the screen below. I could not see any link for signing up. How can I sign up? Thanks!

![Screenshot_20240921_184836](https://github.com/user-attachments/assets/27319d98-5cf9-4f17-a574-89fdee31a9f8)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by taprosoft** [comment]
Just use default credential `admin` / `admin` as mentioned in the docs.
https://cinnamon.github.io/kotaemon/development/

**Comment by destin-v** [comment]
How would someone be able to sign up for a new account if they wanted to use it but was not the admin?  It should be able to serve multiple users.
