### ISSUE TITLE
[BUG] - Windows Installation Failed

### ISSUE THREAD

**Issue by pepeto** [Cinnamon/kotaemon#318]
### Description

![image](https://github.com/user-attachments/assets/1aacfc98-a2fb-4ac9-a6e8-88384bab2576)

### Reproduction steps

```bash
Windows Installation Failed
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by cin-albert** [comment]
@pepeto 
It seems to be an ownership problem of the target folder that you were installing Kotaemon to

Quick fix: open your command prompt and add this command: `git config --global --add safe.directory "*"
` and then try running Kotaemon's install script again
