### ISSUE TITLE
[BUG] - Post installation, the login page is coming again and again, even though the username and password has not been set even once. 

### ISSUE THREAD

**Issue by Akshaya150** [Cinnamon/kotaemon#331]
### Description

Post installation, the login page is coming again and again, even though the username and password has not been set even once. And there is no option to navigate to any other page not even forgot password page is coming up.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by taprosoft** [comment]
Default user name and passwd are `admin` / `admin`, as noted in the main README https://github.com/Cinnamon/kotaemon.
Probably we haven't include it in the user setup so it causes this confusion. Please try the login information above.
