### ISSUE TITLE
[BUG] - <title> GraphRag时报错

### ISSUE THREAD

**Issue by Ruijie-Ysp** [Cinnamon/kotaemon#335]
### Description

NotADirectoryError: [Errno 20] Not a directory: '/app/ktem_app_data/user_data/files/graphrag/8512cbbf-2585-435e-b5ef-e254e9fc26c5/output/stats.json/artifacts/create_final_nodes.parquet'
Updating retrieval history (regen=True)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Ruijie-Ysp** [comment]
![DESCRIPTION](LINK.png)

**Comment by bookandlover** [comment]
same issue.

**Comment by taprosoft** [comment]
Please check the new release.
