### ISSUE TITLE
[BUG] - <title> without docker error

### ISSUE THREAD

**Issue by Smile-L-up** [Cinnamon/kotaemon#337]
### Description

Thank you very much for open-sourcing such a great project. I installed without docker. Deploy according to the following steps:
```python
# optional (setup env)
conda create -n kotaemon python=3.10
conda activate kotaemon

# clone this repo
git clone https://github.com/Cinnamon/kotaemon
cd kotaemon

pip install -e "libs/kotaemon[all]"
pip install -e "libs/ktem"

View and edit your environment variables (API keys, end-points) in .env.

(Optional) To enable in-browser PDF_JS viewer, download PDF_JS_DIST and extract it to libs/ktem/ktem/assets/prebuilt
```
Then run python app.py. When I visit http://localhost:7860/, an error is reported.
```python
error
Connection errored out.
```

Looking forward to your reply.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
```

### Browsers

Chrome

### OS

Linux

### Additional information

Linux autodl-container-52214cb424-950f8e01 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by taprosoft** [comment]
Hi @Smile-L-up please ensure that you install from a fresh environment.
Could you run the Docker approach successfully?

This is a freshly installed Linux env looks like. Please check if there is any dependencies are mismatched.
[requirements.lock.txt](https://github.com/user-attachments/files/17160845/requirements.lock.txt)

**Comment by cin-albert** [comment]
Hi @Smile-L-up, it can be an issue of FastAPI or Pydantic. Can you reinstall these dependencies:  `pip install -U fastapi==0.112.1 pydantic==2.9.1` and run `python app.py` again?

**Comment by Smile-L-up** [comment]
> 你好@Smile-L-up，这可能是 FastAPI 或 Pydantic 的问题。您可以重新安装这些依赖项： `pip install -U fastapi==0.112.1 pydantic==2.9.1`然后`python app.py`再次运行吗？

Thanks for your guidance, it's working fine now.
