### ISSUE TITLE
[BUG] - <title>Uploading text to files>file collection returns error

### ISSUE THREAD

**Issue by ghost** [Cinnamon/kotaemon#347]
### Description

I've tried to upload .txt files and .pdf files to the Files > Files Collection Page. It gives me upload error.
![Screenshot 2024-09-29 154534](https://github.com/user-attachments/assets/806f3a07-e2ef-4283-b6fe-8fc576a23cb7)

### Reproduction steps

```bash
1. Go to 'Files > File Collecctions'
2. Try to upload file
3. See "upload error"
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by ghost** [comment]
Sorry, uploaded wrong image. Here is the correct one showing the "upload error"
![Screenshot 2024-09-29 164434](https://github.com/user-attachments/assets/c63ba004-2da4-4aad-9ce7-47ab95fe3e9c)

**Comment by taprosoft** [comment]
@ecceeecs sorry for the late reply. Could you check your terminal output? Which installation method has you used? Can you try the Docker install method or Online install here https://cinnamon.github.io/kotaemon/online_install/
