### ISSUE TITLE
[REQUEST] - <title>add reranker model

### ISSUE THREAD

**Issue by lionkingc** [Cinnamon/kotaemon#357]
### Summary
I have successfully added "LLM-Chat model" and "embedding model".
Can I add reranker model such as "BAAI/bge-reranker-v2-m3"  or "netease-youdao/bce-reranker-base_v1" from some Api provider?

### Basic Example

curl --request POST \
  --url https://api.siliconflow.cn/v1/rerank \
  --header 'Authorization: Bearer <token>' \
  --header 'Content-Type: application/json' \
  --data '{
  "model": "BAAI/bge-reranker-v2-m3",
  "query": "Apple",
  "documents": [
    "apple",
    "banana",
    "fruit",
    "vegetable"
  ],
  "top_n": 4,
  "return_documents": true,
  "max_chunks_per_doc": 123,
  "overlap_tokens": 79
}'

### Drawbacks

reranker model

**Comment by taprosoft** [comment]
Current we only support https://huggingface.co/docs/text-embeddings-inference/index, which also support your mentioned models.
For you use-case, feel free to contribute your API endpoint as custom reranker to the codebase.
