### ISSUE TITLE
[BUG] - <title>Unable to plot GraphRag

### ISSUE THREAD

**Issue by qingerrrr** [Cinnamon/kotaemon#361]
### Description

I want to plot the knowledge graph for a pdf document, but I am encountering this issue at "create_base_entity_graph" step.
![kotaemon_error](https://github.com/user-attachments/assets/5016e7cf-12c5-4614-b54d-03282022ba31)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

**Comment by taprosoft** [comment]
Please check the latest version and instruction for setting up GraphRAG here https://github.com/Cinnamon/kotaemon#setup-graphrag.
