### ISSUE TITLE
[REQUEST] - export Resources config(LLMs/Embeddings/etc)

### ISSUE THREAD

**Issue by lionkingc** [Cinnamon/kotaemon#363]
After docker pull update kotaemon to v0.6.5, all data still in old Container ,
Is there any way to export data,config/setting after update?

### Basic Example

docker pull ghcr.io/cinnamon/kotaemon:main-full

**Comment by taprosoft** [comment]
When using Docker run command, please add ` -v ./ktem_app_data:/app/ktem_app_data` to store all app data to external `ktem_app_data` which is outside of the container. Later you can backup this folder and re-use them for future Kotaemon version. Also you can use it interchangeably with local install version.
