### ISSUE TITLE
[BUG] End user: No conceptual maps / GraphRAG produced when streaming responses (v0.6.5)

### ISSUE THREAD

**Issue by kakolla** [Cinnamon/kotaemon#368]
### Description

Freshly downloaded the .zip file for v0.6.5. Running windows 11 24H2 and ran run_windows.bat. 

First thing I see in the command prompt is GraphRAG dependencies not installed. I tried installing the dependencies but got this cycle--graphrag needs aiofiles==24.1.0 but gradio 4.44.1 needs aiofiles<24.0. and so on.

gradio 4.44.1 requires aiofiles<24.0,>=22.0, but you have aiofiles 24.1.0 which is incompatible.
graphrag 0.3.5 requires environs<12.0.0,>=11.0.0, but you have environs 9.5.0 which is incompatible.
graphrag 0.3.5 requires tenacity<10.0.0,>=9.0.0, but you have tenacity 8.2.3 which is incompatible.

graphrag 0.3.5 has requirement aiofiles<25.0.0,>=24.1.0, but you have aiofiles 23.2.1.
graphrag 0.3.5 has requirement environs<12.0.0,>=11.0.0, but you have environs 9.5.0.
graphrag 0.3.5 has requirement tenacity<10.0.0,>=9.0.0, but you have tenacity 8.2.3.

Ran cohere's model as well as llama3.1:8b locally but both have the issue.

I have two PDFs uploaded to both the File and GraphRAG section. The 'File Collection' option works fine with a prompt. Running 'GraphRAG Collection' with the same prompt says it retrieves 0 documents and produces a general output without any graph.

My question: is GraphRAG implemented in Kotaemon, or is there concept map being produced because of a dependency issue on my end?

### Reproduction steps

```bash
1. Run the windows version of the bat file
2. Select cohere and input API key
3. Upload 2 PDFs to both the File Collection and GraphRAG Collection area and index.
4. Ask a prompt about one of the files with File Collection--Search all turned on. It should work an retrieve the correct page.
5. Ask the same prompt with GraphRAG Collection--Search all turned on. Doesn't produce a graph and instead outputs a general response.
```

### Screenshots

```bash
https://imgur.com/a/yuLu7PW
```

### Logs

```bash
Thinking ...
Retrievers [DocumentRetrievalPipeline(DS=<kotaemon.storages.docstores.lancedb.LanceDBDocumentStore object at 0x0000022EFD66D1B0>, FSPath=WindowsPath('C:/Users/abhis/Desktop/Kotaemon/kotaemon-main/ktem_app_data/user_data/files/index_1'), Index=<class 'ktem.index.file.index.IndexTable'>, Source=<class 'ktem.index.file.index.Source'>, VS=<kotaemon.storages.vectorstores.chroma.ChromaVectorStore object at 0x0000022EFD66D450>, get_extra_table=False, llm_scorer=LLMTrulensScoring(concurrent=True, normalize=10, prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x0000022E842887C0>, system_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x0000022E8428A590>, top_k=3, user_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x0000022E8428B9D0>), mmr=False, rerankers=[CohereReranking(cohere_api_key='Eo7OoxbsITNfbU9wFGavhzCL8e7LE8NHZ1HidzjD', model_name='rerank-multilingual-v2.0')], retrieval_mode='hybrid', top_k=10, user_id=1), GraphRAGRetrieverPipeline(DS=<theflow.base.unset_ object at 0x0000022EC60417B0>, FSPath=<theflow.base.unset_ object at 0x0000022EC60417B0>, Index=<class 'ktem.index.file.index.IndexTable'>, Source=<theflow.base.unset_ object at 0x0000022EC60417B0>, VS=<theflow.base.unset_ object at 0x0000022EC60417B0>, file_ids=[], user_id=<theflow.base.unset_ object at 0x0000022EC60417B0>)]
searching in doc_ids []
Got 0 retrieved documents
len (original) 0
Got 0 images
Trying LLM streaming
Got 0 cited docs
User-id: 1, can see public conversations: True
```

### Browsers

Microsoft Edge

### OS

Windows

**Comment by taprosoft** [comment]
Please check the latest version and instruction for setting up GraphRAG here https://github.com/Cinnamon/kotaemon#setup-graphrag.
