### ISSUE TITLE
The answer returns as in the attached image. Is it because I didn't name the file?

### ISSUE THREAD

**Issue by cin-jimmy** [Cinnamon/kotaemon#37]
Given that I have followed all the steps from adding the AI model and select the uploaded file.
[Uploading HBR.pdf…]()
![image](https://github.com/Cinnamon/kotaemon/assets/54021405/14f23f85-54f8-4cc6-9b20-a0b497bdcec0)

While in the terminal
![image](https://github.com/Cinnamon/kotaemon/assets/54021405/3d06896e-6f76-47dd-9a05-bea940373146)

**Comment by lone17** [comment]
Yes unfortunately it doesn't understand meta question currently. Meaning it has no conception of `file`, it only knows the content of the files. We will incorporate the ability to understand meta questions in future updates.
