### ISSUE TITLE
[BUG] Model open ai not found in initial setup. 

### ISSUE THREAD

**Issue by Abner77** [Cinnamon/kotaemon#378]
### Description

I have downloaded the 0.6.6 release source code and copied to the folder. Execute with python app.py so it starts the setup, when I select the open ai model and introduce my token and click Proceed, i get this error in the console. What's going on?

(kotaemon) C:\Users\David\kotaemon>python app.py
sagemaker.config INFO - Not applying SDK defaults from location: C:\ProgramData\sagemaker\sagemaker\config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: C:\Users\David\AppData\Local\sagemaker\sagemaker\config.yaml
GraphRAG dependencies not installed. GraphRAG retriever pipeline will not work properly.
User "admin" created successfully
Setting up quick upload event
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
User-id: None, can see public conversations: False
User-id: 1, can see public conversations: True
Traceback (most recent call last):
  File "C:\Users\David\kotaemon\libs\ktem\ktem\llms\manager.py", line 208, in update
    raise ValueError(f"Model {name} not found")
ValueError: Model openai not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\David\anaconda3\envs\kotaemon\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\David\anaconda3\envs\kotaemon\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\David\anaconda3\envs\kotaemon\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\Users\David\anaconda3\envs\kotaemon\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\David\anaconda3\envs\kotaemon\lib\site-packages\gradio\utils.py", line 663, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\David\anaconda3\envs\kotaemon\lib\site-packages\gradio\utils.py", line 656, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\David\anaconda3\envs\kotaemon\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\David\anaconda3\envs\kotaemon\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "C:\Users\David\anaconda3\envs\kotaemon\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "C:\Users\David\anaconda3\envs\kotaemon\lib\site-packages\gradio\utils.py", line 639, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\David\anaconda3\envs\kotaemon\lib\site-packages\gradio\utils.py", line 801, in gen_wrapper
    response = next(iterator)
  File "C:\Users\David\kotaemon\libs\ktem\ktem\pages\setup.py", line 201, in update_model
    llms.update(
  File "C:\Users\David\kotaemon\libs\ktem\ktem\llms\manager.py", line 213, in update
    raise ValueError(f"Failed to update model {name}: {e}")
ValueError: Failed to update model openai: Model openai not found
Keyboard interruption in main thread... closing server.
Traceback (most recent call last):
  File "C:\Users\David\anaconda3\envs\kotaemon\lib\site-packages\gradio\blocks.py", line 2690, in block_thread
    time.sleep(0.1)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Microsoft Edge

### OS

Windows

**Comment by taprosoft** [comment]
@Abner77 please check if `.env` in the release zip file are copied to your root folder (together with `flowsettings.py` and `app.py`). Missing this file can cause this issue.

**Comment by Abner77** [comment]
Thanks taprosoft, you are right. I have created the .env and now I don't see errors in the console, however, when i cllick proceed, it shows like is sending hi but nothing happens...
Also with ollama, same issue (i have installed and it's working in the terminal with llama3.1:8b)
![image](https://github.com/user-attachments/assets/4bcbd2f3-370e-403b-a6bc-32c1b489be84)
![image](https://github.com/user-attachments/assets/3334d22b-52ad-4225-b23c-1ac5ed87b173)

**Comment by taprosoft** [comment]
@Abner77 It seems weird, actually it is testing embedding model in the first step. Can you skip the setup process, select Ollama embedding / LLM model and test them separately: https://github.com/Cinnamon/kotaemon/blob/main/docs/local_model.md

**Comment by Abner77** [comment]
![image](https://github.com/user-attachments/assets/e0f5cf9d-fd72-49a6-853c-7a037b7860a3)
![image](https://github.com/user-attachments/assets/b13da5f0-5d48-485c-a2c9-c07b806b20d7)


Same behaviour. Does not answer....

**Comment by Abner77** [comment]
I've done the setup on ubuntu, it works. Same procedure. Created conda environment, copied source code 0.6.5 to the folder kotaemon, pip install pip install as said in the guide, created .env, python app.py, setup ollama, admited, enter logon, working no problems. 
Windows, I have recreated everything, to test if I have done anything wrong or whatever.... same as before does not answer..... 

What module or where should i place the vscode debugger to see what's happening? @taprosoft

**Comment by taprosoft** [comment]
@Abner77 from Kotaemon we just using the OpenAPI compatible API from Ollama:
https://ollama.com/blog/openai-compatibility

May be you can try a simple curl and observe Ollama server log, or using Python example in the above document to check for some potential issues>

**Comment by Abner77** [comment]
@taprosoft python example runs no problem
![image](https://github.com/user-attachments/assets/d556eee7-254e-4efc-8b9c-d70a5bf664da)

**Comment by taprosoft** [comment]
@Abner77 anything on the log of Kotaemon server when you press the Test connection button which might help? Or it just froze indefinitely?

**Comment by Abner77** [comment]
Nothing, it just freezes. I'm trying to debug and this is quite complex. I'm using the test connection in resources and when it goes through this line  respond = llm("Hi")  in \kotaemon\libs\ktem\ktem\llms\ui,py  instead of going to the class that it's llm (which in theory is chatopenai (derived from BaseChatOpenAI) in module \kotaemon\libs\kotaemon\kotaemon\llms\chats\openai.py the code execution goes to a file called anaconda3\envs\kotaemon\Lib\site-packages\theflow\base.py __call__   These goes beyond me, my python is not quite there to understand this weird behaviour. I dont know what to look there. I have breakpoints in openai.py all over the place but none is being hit. @taprosoft  Thanks for the effort man.

**Comment by Abner77** [comment]
I've been able to trace the code to this line i show in the image where I have put a breakpoint, in that line, the debugger does nothing, like it gets literally locked there. The module is in anaconda3\envs\kotaemon\Lib\site-packages\theflow\cache\filebased.py
![image](https://github.com/user-attachments/assets/5373566a-634e-400e-8fdf-0bbe0a07cd46)

Any ideas @taprosoft ? Anyone?

**Comment by taprosoft** [comment]
@Abner77 The issue seems to be you are lacking this part
```
:: Workaround for diskcache path with folder start with .
SET THEFLOW_TEMP_PATH=flow_tmp
```
Please check if this environment variable is set before you run `python app.py`

**Comment by Abner77** [comment]
Now it's finally working, thank you so much @taprosoft

**Comment by taprosoft** [comment]
Great.
