### ISSUE TITLE
[REQUEST] VLLM Support

### ISSUE THREAD

**Issue by micuentadecasa** [Cinnamon/kotaemon#379]
### Reference Issues

NA

### Summary

I would like to know how to configure VLLM as LLM

### Basic Example

I have Mistral and LLama running in VLLM and would like to configure them in Kotaemon

### Drawbacks

I need it running with VLLM

**Comment by taprosoft** [comment]
Hi @micuentadecasa you can totally do something like this: https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html
Start VLLM OpenAI compatible server and add new new OpenAI-based model in resources with modified `base_url`

**Comment by micuentadecasa** [comment]
@taprosoft  many thanks for the info

**Comment by micuentadecasa** [comment]
thanks for the fast support
