### ISSUE TITLE
Embedding Model

### ISSUE THREAD

**Issue by jeff52415** [Cinnamon/kotaemon#38]
When I follow default set up embedding model, it show: 
`ImportError: cannot import name 'TextEmbedding' from 'fastembed' (unknown location)`

But when I register OpenAI Embedding Model and delete old one, it show
`KeyError: 'local-bge-base-en-v1.5'`

I have attached detail error in screenshot below:

![截圖 2024-04-17 上午11 38 54](https://github.com/Cinnamon/kotaemon/assets/25951918/9fdfca94-ed8c-4d0d-a512-bd5d391be473)
![截圖 2024-04-17 上午11 38 46](https://github.com/Cinnamon/kotaemon/assets/25951918/7f587dda-1eb7-42f0-9717-57cd4d0c0db8)

**Comment by lone17** [comment]
> When I follow default set up embedding model, it show: `ImportError: cannot import name 'TextEmbedding' from 'fastembed' (unknown location)`
> 
> But when I register OpenAI Embedding Model and delete old one, it show `KeyError: 'local-bge-base-en-v1.5'`
> 
> I have attached detail error in screenshot below:
> 
> ![截圖 2024-04-17 上午11 38 54](https://private-user-images.githubusercontent.com/25951918/323052949-9fdfca94-ed8c-4d0d-a512-bd5d391be473.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjE4MjMsIm5iZiI6MTcxMzg2MTUyMywicGF0aCI6Ii8yNTk1MTkxOC8zMjMwNTI5NDktOWZkZmNhOTQtZWQ4Yy00ZDBkLWE1MTItYmQ1ZDM5MWJlNDczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA4Mzg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NWM3Y2RmMDMwMGI4OWQwOTg1ZTVmMmNiYzE0ZjYyNjYxMTI3MDM0Mjc0MDczNjg5YzRjZmI5Njc2ZDM0OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.na69QTGbIKQGgkaezIIEWnxSWHF0P-1sGcLUaVVTAzs) ![截圖 2024-04-17 上午11 38 46](https://private-user-images.githubusercontent.com/25951918/323052951-7f587dda-1eb7-42f0-9717-57cd4d0c0db8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjE4MjMsIm5iZiI6MTcxMzg2MTUyMywicGF0aCI6Ii8yNTk1MTkxOC8zMjMwNTI5NTEtN2Y1ODdkZGEtMWViNy00MmYwLTk3MTctNTdjZDRkMGMwZGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA4Mzg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYjRjNzgyZmZkZTRjMjdiYWJmMGE5YmM5ZWY0YzYyNWVmZjk5NTJiZGQ1M2VmOWY4OTNkZDllYTUwYzc2MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4i_AMZRF8871WiW__t9U-6IXn0GeKSwjFUUsQWK46oQ)

This has been fixed in the latest version. So currently you can solve this using one of these 3 options:
- download and install the latest version
- manually install `fastembed` to the conda environment
- the `Key Error` happens because the `Index` was configured using the deleted embedding model, so you can solve this by edit the configure of the `Index` in the Resource -> Index tab
