### ISSUE TITLE
[BUG] Todays (20241010) Docker Images: Only arm64 Arch Is Available

### ISSUE THREAD

**Issue by GeorgiaM-honestly** [Cinnamon/kotaemon#381]
### Description

While trying to pull todays (20241010) docker images on Linux on amd64, the following error is thrown:

no matching manifest for linux/amd64 in the manifest list entries

Performing a docker manifest inspect reveals that only arm64 is listed.

### Reproduction steps

```bash
1. docker pull "ghcr.io/cinnamon/kotaemon:main-full"
2. Observe the error: no matching manifest for linux/amd64 in the manifest list entries
3. Inspect the manifiest: docker manifiest inspect "ghcr.io/cinnamon/kotaemon:main-full"
4. Observe that only arm64 is listed
```

### OS

Linux

### Additional information

I am observing this issue on more than one linux system on different networks

**Comment by Jainbaba** [comment]
@GeorgiaM-honestly  Can you run `docker info` and show the output?

**Comment by taprosoft** [comment]
@GeorgiaM-honestly confirm this issue. We will release a fix soon for this.

**Comment by taprosoft** [comment]
@GeorgiaM-honestly please check the latest image
