### ISSUE TITLE
Showing Error Message

### ISSUE THREAD

**Issue by jeff52415** [Cinnamon/kotaemon#39]
We might have to find better way to handle error and inform user, when there is issue in embedding process, UI show no Error and I could only refer back to terminal to check,

**Comment by lone17** [comment]
> We might have to find better way to handle error and inform user, when there is issue in embedding process, UI show no Error and I could only refer back to terminal to check,

That's a limitation of using Gradio, we could show error through a toast noti, but that won't be persistent and the terminal is still needed.
