### ISSUE TITLE
[BUG] Using local VLLM, issue with the context length

### ISSUE THREAD

**Issue by micuentadecasa** [Cinnamon/kotaemon#395]
### Description

I changed OpenAI to local VLLM server compatible with OpenAI, but now I´m getting an error saying that the context length for my model is exhausted.
How can I reduce the maximum number of tokens to be sent to the LLM?

### Reproduction steps

```bash
1. change openai to VLLM compatible API
2. do a query in the chat
3. the limit for the context window is raised
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by taprosoft** [comment]
@micuentadecasa You can set the setting in Reasoning settings > Max context length

![image](https://github.com/user-attachments/assets/21ffb11a-c6dc-41b0-804b-ec67553fcd60)

**Comment by micuentadecasa** [comment]
@taprosoft many thanks, I supppose it also can be modified in the flowsettings.py

**Comment by micuentadecasa** [comment]
One question @taprosoft , I know that the bug is closed, but I have another question, the limit for my model is 6900 tokens, I tried to change the limit to 6000, 5000, and 4000, with 4000 started to work, why do I have to reduce it to 4000?

**Comment by taprosoft** [comment]
@micuentadecasa no problems. This may be because of different tokenizer was used. By default tokens are counted based on OpenAI GPT https://platform.openai.com/tokenizer
Which might be longer for open-source models especially on non-English language.
