### ISSUE TITLE
[BUG] When saving reasoning settings the language seems to change (when using new languages)

### ISSUE THREAD

**Issue by micuentadecasa** [Cinnamon/kotaemon#401]
### Description

I put Spanish as language in the flowsettings.py file, I runt it with Docker and the responses were in Spanish, I had to change the Max Content lenght in the UI, and from there the responses are mainly in English, but in the UI still appears Spanish.

### Reproduction steps

```bash
1. add a new language in flowsettings.py, and put it as default (spanish in my case) 
2. Go to 'Reasoning settings'
3. change max content length
4. save
4. the responses are in English
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by taprosoft** [comment]
@micuentadecasa currently UI language option is not working for now since we haven't implemented a way to use translation file to change UI content. Please wait for this feature or contribute a PR. Thanks

**Comment by micuentadecasa** [comment]
humm, strange, because when I changed it in the code, it started to reply in Spanish, so it seems to me that is more an issue when saving the settings that overwrites the option.

**Comment by taprosoft** [comment]
@micuentadecasa That options only affect the prompt to the LLM so the generated answer will be in the target language. However UI language switch is currently not supported.

**Comment by micuentadecasa** [comment]
I mean that, the generated answer was in Spanish until I click on save settings, sorry for the confusion.
