### ISSUE TITLE
[REQUEST] Support for Alternative GraphRAG Implementation (e.g., LightRAG) Instead of Microsoft GraphRAG

### ISSUE THREAD

**Issue by EvelynBai** [Cinnamon/kotaemon#406]
### Summary

Thank you for this fantastic project! As a newcomer to GraphRAG, I’ve learned so much from your work, and I truly appreciate the effort you’ve put into it.

I have a request: I’d like to use an alternative GraphRAG implementation (such as [light RAG](https://github.com/HKUDS/LightRAG), as it has a lower token consumption compared to Microsoft GraphRAG). Could you please let me know which files I would need to modify to make this change? Additionally, it would be incredibly helpful if you could include instructions for this in the developer guide.

Thank you so much for your time and support;)!!!

### Basic Example

Use an alternative GraphRAG implementation (e.g., light RAG)

### Drawbacks

It might require a lot of work, like needing to change a bunch of code.

**Comment by taprosoft** [comment]
Hi @EvelynBai thanks for the suggestion.

Please check this similar request https://github.com/Cinnamon/kotaemon/issues/243 first.
We are planning to integrate `nano-graphrag` implementation which also is the back-end of LightRAG. However, if you can contribute PRs, it would be great.

The implementation of GraphRAG can be found at https://github.com/Cinnamon/kotaemon/blob/main/libs/ktem/ktem/index/file/graph/pipelines.py.

**Comment by EvelynBai** [comment]
> Hi @EvelynBai thanks for the suggestion.
> 
> Please check this similar request #243 first. We are planning to integrate `nano-graphrag` implementation which also is the back-end of LightRAG. However, if you can contribute PRs, it would be great.
> 
> The implementation of GraphRAG can be found at https://github.com/Cinnamon/kotaemon/blob/main/libs/ktem/ktem/index/file/graph/pipelines.py.

Thank you!! I'll try❤️

**Comment by taprosoft** [comment]
Closed https://github.com/Cinnamon/kotaemon/releases/tag/v0.7.4
