### ISSUE TITLE
Users can View and Download each others documents

### ISSUE THREAD

**Issue by scalenow** [Cinnamon/kotaemon#411]
### Description

A normal user was created by admin ,however logging as normal user ,documents uploaded by other users and admin can be accessed by the normal user .

This seems to breach data privacy guidelines

### Reproduction steps

```bash
1. Uploaded documents as admin 
2. Loggedout and loggedi as normal user 
3  Under files documents of admin can be accessed and downloaded
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
https://1drv.ms/i/s!ArxcgrQLWyIkj6dXqjdKtLuyamMXXg?e=yngTAc
```

### Browsers

Firefox, Chrome, Safari

**Comment by taprosoft** [comment]
Please check this similar issue. https://github.com/Cinnamon/kotaemon/issues/177

**Comment by scalenow** [comment]
Sorry @taprosoft cannot understand what you mean

**Comment by taprosoft** [comment]
Sorry I forgot to attach the link. Fixed.

**Comment by scalenow** [comment]
@taprosoft " Hi, by default File Collection is public, meaning all users can access and delete the files uploaded to it. You can go to Resources > File Collections > set private: true to restrict access to only owner of that file.
Alternatively, add a new Collection that is private and your users can upload to both depend on whether on they are planning to share their file with others or not."


Please advise how to access Resources > File Collections > set private: true.see the screenshot there is no File Collections
<img width="1458" alt="Screenshot 2024-10-19 at 1 27 47 am" src="https://github.com/user-attachments/assets/2401f1e3-03f3-46ac-8008-aef6cd3b5fd2">

**Comment by taprosoft** [comment]
![image](https://github.com/user-attachments/assets/926f4ab8-d055-47b7-8f40-db1a21633b8f)
This one

**Comment by scalenow** [comment]
Thanks it worked
