### ISSUE TITLE
[BUG] text with overlapping characters and distorted formatting

### ISSUE THREAD

**Issue by pvl** [Cinnamon/kotaemon#420]
### Description

The app occasionally displays text incorrectly with overlapping characters and distorted formatting, as seen in the attached image (table from the list of files in a collection). This affects the readability and usability of the interface, particularly when handling PDF documents or lists with long filenames. <img width="807" alt="to_upload_gpt" src="https://github.com/user-attachments/assets/49dc58d6-9738-4563-bb38-dbd2ff37b762">

### Reproduction steps

```bash
1. Go to a collection and upload files with long file names (eg 40 chars)
2. See the table with list of files and bad formatting
```

### Screenshots

```bash
![Example screenshot](https://github.com/user-attachments/assets/49dc58d6-9738-4563-bb38-dbd2ff37b762)
```

### Browsers

Firefox

### OS

MacOS

**Comment by rlabs-oss** [comment]
Safari doesn't exhibit the same issue.

**Comment by vap0rtranz** [comment]
Firefox on Linux has this issue too.

**Comment by vap0rtranz** [comment]
I don't see this text display issue anymore.  Fixed?

I'm running latest Docker main-full image.

**Comment by taprosoft** [comment]
@vap0rtranz @pvl this is CSS formatting issue which happens on Firefox.
Suppose to be fixed in the latest release.
