### ISSUE TITLE
[REQUEST] Supports LLM API provider : Google

### ISSUE THREAD

**Issue by llkdd1** [Cinnamon/kotaemon#428]
### Reference Issues

Supports LLM API provider : Google
we could use: Gemini, Gemini-pro

### Summary

Supports LLM API provider : Google
we could use: Gemini, Gemini-pro

### Basic Example

Supports LLM API provider : Google
we could use: Gemini, Gemini-pro

### Drawbacks

Supports LLM API provider : Google
we could use: Gemini, Gemini-pro

**Comment by taprosoft** [comment]
Did you check this option? We already provide support for Gemini (Google Generative AI) API
![image](https://github.com/user-attachments/assets/0daadef3-f94a-4bfc-8c88-a1e7f22210d3)

**Comment by llkdd1** [comment]
But this is only for files, I need the graphrag for Gemini
