### ISSUE TITLE
[BUG] LignhtRGA not working

### ISSUE THREAD

**Issue by bookandlover** [Cinnamon/kotaemon#480]
### Description

with the below .env settings, there is no Lightrag Botton in File Colletions. My python version is 3.10.
# set to true if you want to use customized GraphRAG config file
USE_CUSTOMIZED_GRAPHRAG_SETTING=true
USE_NANO_GRAPHRAG=true
USE_LIGHTRAG=true

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

MacOS

**Comment by taprosoft** [comment]
@bookandlover currently USE_NANO_GRAPHRAG and USE_LIGHTRAG are mutually exclusive. Set only once variable to True.
However you just need to run Kotaemon once with these env var for the corresponding collection to appear. You can try running 2 times with each var set to True separately and later you can use both collections.

**Comment by chenchen333-dev** [comment]
> 目前USE_NANO_GRAPHRAG 和 USE_LIGHTRAG 是互斥的。仅将 one 变量设置为 True。但是，您只需使用这些 env var 运行 Kotaemon 一次，即可显示相应的集合。您可以尝试运行两次，将每个 var 分别设置为 True，然后您可以使用两个集合。

I'm having the same issue. In addition, nano-graphRAG is installed, which is not shown in the page

![Image](https://github.com/user-attachments/assets/25d4bb11-617d-406a-8ec0-b60887a719a8)

**Comment by chenchen333-dev** [comment]
> 目前USE_NANO_GRAPHRAG 和 USE_LIGHTRAG 是互斥的。仅将 one 变量设置为 True。但是，您只需使用这些 env var 运行 Kotaemon 一次，即可显示相应的集合。您可以尝试运行两次，将每个 var 分别设置为 True，然后您可以使用两个集合。

How to solve it？I'm having the same issue. In addition, nano-graphRAG is installed, which is not shown in the page.

**Comment by chenchen333-dev** [comment]
> 目前USE_NANO_GRAPHRAG 和 USE_LIGHTRAG 是互斥的。仅将 one 变量设置为 True。但是，您只需使用这些 env var 运行 Kotaemon 一次，即可显示相应的集合。您可以尝试运行两次，将每个 var 分别设置为 True，然后您可以使用两个集合。



> 目前USE_NANO_GRAPHRAG 和 USE_LIGHTRAG 是互斥的。仅将 one 变量设置为 True。但是，您只需使用这些 env var 运行 Kotaemon 一次，即可显示相应的集合。您可以尝试运行两次，将每个 var 分别设置为 True，然后您可以使用两个集合。

具体怎么操作呢，在docker 命令中设置了-e USE_NANO_GRAPHRAG=true,在kotaemon中nano-GraphRAG能正常用来聊天，而使用LightRAG能成功创建索引，但无法检索信息，问任何问题都会返回(Sorry, I don't know)
How to do it, set -e USE_NANO_GRAPHRAG=true in the docker command, nano-GraphRAG can be used for chatting normally in kotaemon, and LightRAG can successfully create indexes, but the information cannot be retrieved, and any questions will be returned (Sorry, I don't know)
