### ISSUE TITLE
[BUG] Gradio Version Conflict in Development Environment Setup

### ISSUE THREAD

**Issue by Lee-Ju-Yeong** [Cinnamon/kotaemon#485]
### Description

During the development environment setup, there is a version conflict between kotaemon and gradio packages. While the application runs without apparent issues, pip reports a dependency conflict warning.

### Reproduction steps

```bash
Create and activate conda environment:
conda create -n kotaemon python=3.10
conda activate kotaemon


Install development packages:
pip install -e "libs/kotaemon[all]"
pip install -e "libs/ktem"
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
Attempting uninstall: gradio
  Found existing installation: gradio 3.50.2
  Uninstalling gradio-3.50.2:
    Successfully uninstalled gradio-3.50.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
kotaemon 0.7.8 requires gradio<4.0,>=3.50.2, but you have gradio 4.44.1 which is incompatible.
```

### Browsers

Chrome

### OS

Windows

### Additional information

Additional information
Current installed gradio version: 4.44.1
Required gradio version by kotaemon: >=3.50.2, <4.0
Despite the version conflict, the application (app.py) appears to run normally
This might need attention in future releases to ensure compatibility

**Comment by taprosoft** [comment]
It is weird since the current version pinning for Gradio is defined here: https://github.com/Cinnamon/kotaemon/blob/5b828c213c1d997fcd0e7ef40cd2b207fe2797c1/libs/kotaemon/pyproject.toml#L31
Your still looks valid and should work just fine.

**Comment by Lee-Ju-Yeong** [comment]
In [ktem/pyproject.toml](https://github.com/Cinnamon/kotaemon/blob/5b828c213c1d997fcd0e7ef40cd2b207fe2797c1/libs/ktem/pyproject.toml#L29C10-L29C23)[ktem/pyproject.toml], there's a notation "gradio>=4.31.0,<5". Could this be affecting things? Why am I getting this error message? What solutions can I try?"

**Comment by Lee-Ju-Yeong** [comment]
thank you so much for kind answer.
