### ISSUE TITLE
[BUG] nano-graphrag stuck on 'writing graph with xxx nodes, xxx edges' step

### ISSUE THREAD

**Issue by EvelynBai** [Cinnamon/kotaemon#508]
### Description

I was testing Nano-GraphRAG with the Doubao LLM via API, and everything worked fine until I encountered the following log message:
![截屏2024-11-20 下午2 30 48](https://github.com/user-attachments/assets/d937ce32-9416-40e2-b79a-9a08cd87c10d)
At this point, the process seems to hang indefinitely—I’ve been stuck here for over 2 hours and am unsure how to proceed.
Could you please assist me in resolving this issue? Any advice or troubleshooting tips would be greatly appreciated.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by EvelynBai** [comment]
By the way, I was wondering which graph database Nano-GraphRAG uses in Kotaemon?

**Comment by taprosoft** [comment]
Can you try the CLI from `nano-graphrag` first to make sure that this is not an issue from it? https://github.com/gusye1234/nano-graphrag
By default I think they use `NetworkX` simple storage and we have not customize that.

**Comment by taprosoft** [comment]
Also, if this is confirmed from `nano-graphrag` side, raising the issue in the original repo might bring more insights.
