### ISSUE TITLE
[REQUEST] Supports Google's Embeddings Model

### ISSUE THREAD

**Issue by HerSophia** [Cinnamon/kotaemon#521]
### Summary

Supports these Google's Embeddings Model
![image](https://github.com/user-attachments/assets/96a2e0ae-bc11-4650-9cab-7a38fe897262)

### Basic Example

I hope this project will support Google's embedding model

### Drawbacks

Slight increase in complexity

**Comment by RubanAgnesh** [comment]
I too am waiting for this because Cohere gets rate limited quite easily. I have a real bad time pulling in docs.

**Comment by umeshkumarasamy** [comment]
Cohere gets rate limited quite easily. I have a real bad time pulling in documents into Kotaemon.

**Comment by taprosoft** [comment]
@umeshkumarasamy We are workin on this in our backlog. Stay tuned!
