### ISSUE TITLE
creating smaller release installer for end users

### ISSUE THREAD

**Issue by lone17** [Cinnamon/kotaemon#53]
It's unnecessary for end users to download the whole repo

**Comment by trducng** [comment]
@lone17 You mean the dependency?
The whole repo in zip file is actually not much, just 7.4 MB in zip file

**Comment by lone17** [comment]
@trducng smaller in terms of the number of files. The whole repo has a lot of files and it looks bloated and unnecessary. Also downloading the entire repo makes upgrading depend on git instead of pip which less desirable. You can check a sample release I'm working on on the releases page https://github.com/Cinnamon/kotaemon/releases
