### ISSUE TITLE
[BUG] how to log-in, when I am running kotaemon with docker

### ISSUE THREAD

**Issue by Dharmogata** [Cinnamon/kotaemon#532]
### Description

![스크린샷 2024-11-27 17-57-00](https://github.com/user-attachments/assets/6771d738-92ce-4217-b297-0e1cbee40c51)

I am running this app with docker. but I can not log in. how to login it?

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Linux

**Comment by tknrych** [comment]
Did you change the default username and passowrd? If not, you can login with admin / admin. Please refer to the following document. 
[https://github.com/Cinnamon/kotaemon](url)

**Comment by Dharmogata** [comment]
@tknrych 
Thank you! I got it.
