### ISSUE TITLE
[BUG] How to customize env and flowsettings.py in doocker

### ISSUE THREAD

**Issue by S4Spares** [Cinnamon/kotaemon#537]
### Description

Would like to change vector store to qdrant or milvius.
How do I customize this in docker

### Reproduction steps

```bash
Run via docker full image
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by taprosoft** [comment]
You can use the volume mount:
`-v your_path/flowsettings.py:/app/flowsettings.py` in `docker run` to override the setting in the Docker container with the file on your host machine.
