### ISSUE TITLE
[BUG] repeat CITATION

### ISSUE THREAD

**Issue by newbie-Li** [Cinnamon/kotaemon#560]
### Description

repeat CITATION

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![image](https://github.com/user-attachments/assets/441f9bfa-32f2-4e9d-84eb-febc645997c7)

**Comment by taprosoft** [comment]
Working on a fix for this.
