### ISSUE TITLE
[BUG] GraphRAG dependencies not installed. Try pip install graphrag future to install. GraphRAG retriever pipeline will not work properly.

### ISSUE THREAD

**Issue by gokulcoder7** [Cinnamon/kotaemon#566]
### Description

Starting Kotaemon UI... (prebuilt PDF.js is at F:\rag\kotaemon-app\kotaemon-app\libs\ktem\ktem\assets\prebuilt\pdfjs-4.0.379-dist)
GraphRAG dependencies not installed. Try pip install graphrag future to install. GraphRAG retriever pipeline will not work properly.
LightRAG dependencies not installed. Try pip install git+https://github.com/HKUDS/LightRAG.git to install. LighthRAG retriever pipeline will not work properly.
Nano-GraphRAG dependencies not installed. Try pip install nano-graphrag to install. Nano-GraphRAG retriever pipeline will not work properly.
User "admin" already exists
Setting up quick upload event
Running on local URL:  http://127.0.0.1:7860

To create a public link, set share=True in launch().
User-id: None, can see public conversations: False
User-id: 1, can see public conversations: True

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Firefox

### OS

Windows

**Comment by gokulcoder7** [comment]
Why closed this issue ?

**Comment by robinszeto** [comment]
This issue also applicable to me. Why Toprosoft close this? Any solution?

**Comment by gokulcoder7** [comment]
> This issue also applicable to me. Why Toprosoft close this? Any solution?
> 




I am waiting for solution

**Comment by someone132s** [comment]
> > This issue also applicable to me. Why Toprosoft close this? Any solution?
> 
> I am waiting for solution

have u found the soultion? i'm facing the same issue

**Comment by taprosoft** [comment]
To install graphRAG, you need to get familiar with the command line:

```
source "install_dir/conda/etc/profile.d/conda.sh" # conda init
conda activate install_dir/env

# for graphrag
pip install "graphrag<=0.3.6" future

# for lightrag
pip install transformers aioboto3 nano-vectordb ollama xxhash "lightrag-hku<=0.0.8"
```

checkout this notebook for example
https://colab.research.google.com/drive/1eTfieec_UOowNizTJA1NjawBJH9y_1nn#scrollTo=dR8EMxWnVfH2

Currently there is no easy way to do it with the setup script. Either use Docker install with preinstalled GraphRAG or https://cinnamon.github.io/kotaemon/online_install/ method.

**Comment by someone132s** [comment]
I'm currently installing it with docker, using docker compose. The problem above is the situation when installing it with docker. I'll set up a new vm and thy to build from source.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
