### ISSUE TITLE
[BUG] error with AsyncCompletions.create

### ISSUE THREAD

**Issue by Sonson6** [Cinnamon/kotaemon#579]
### Description

I pulled 0.9.9 today to take advantage of the new features on nano-graphrag and especially the quicker indexing time thanks to asynchronous call but I keep facing a "coroutine AsyncCompletions.create was never awaited" message. After this message, all my calls fails until reaching 3 failed retries.

I double checked my nano-graph configuration and also made sure my AzureOpenAI server accepts asynchronous calls.

**Comment by taprosoft** [comment]
@Sonson6 this is due to an implementation mistake in AzureOpenAI model. Will update a fix soon. Meanwhile you can try to use normal OpenAI and other models.

**Comment by RayDean** [comment]
the problem when I use LightRAG indexing, did you solved the problem?

**Comment by RayDean** [comment]
same problem when I use LightRAG indexing, did you solved the problem?

**Comment by Sonson6** [comment]
Yes. I changed this line https://github.com/Cinnamon/kotaemon/blob/95191f53d9ee54d40bc78885a6bf706b29ea4a9a/libs/kotaemon/kotaemon/llms/chats/openai.py#L214 by : 

```python
resp = await self.openai_response(
            client, messages=input_messages, stream=False, **kwargs
        )
resp = resp.dict()
```
