### ISSUE TITLE
citation not working on simple pipeline

### ISSUE THREAD

**Issue by lone17** [Cinnamon/kotaemon#70]

**Comment by khankaholic** [comment]
a @lone17 I think the current implementation incorrectly accesses `function_output` from `llm_output`, causing an error. It should access additional_kwargs from the first message in messages, since we only run one LLM function call to extract citation.
**original:** https://github.com/Cinnamon/kotaemon/blob/56dfc8fb53965f3000c00a3f0e2449ac8363d875/libs/kotaemon/kotaemon/indices/qa/citation.py#L108-L110

**and it should like this:**
`function_output = llm_output.messages[0].additional_kwargs["tool_calls"][0]["function"]["arguments"]`

**Comment by khankaholic** [comment]
fyi, an example of `llm_output`:

> (Pdb) llm_output
> LLMInterface(content='', id_='5141bae1-0183-45a0-b895-5fcea176c82d', candidates=[''], completion_tokens=582, total_tokens=3865, prompt_tokens=3283, messages=[AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'call_hrW3xO0IxFeCAMeIvFoWb1Sh', 'function': {'arguments': '{\n  "question": "MVAについて説明してください。",\n  "answer": [\n    {\n      "fact": "MVA（Market Value Added）は、投資家がその企業に対してどれだけの価値を認めているかを示します。これは、企業の市場価値（株価などによって決まる）と、その企業が実際に持っている資産の価値（会社の総資産）との差です。",\n      "substring_quote": ["MVA（Market Value Added：市場付加価値）", "MVAは、投資家がその企業に対してどれだけの価値を認めているかを示します。これは、企業の市場価値（株価などによって決まる）と、その企業が実際に持っている資産の価値（会社の総資産）との差です。"]\n    },\n    {\n      "fact": "MVAは企業全体の市場価値から投下資本を差し引いた金額であり、「企業が投下資本を上回る価値をどれだけ創造できたか」を示す指標です。",\n      "substring_quote": ["Value Added：市場付加価値）", "・企業全体の市場価値から投下資本を差し引いた金額であり", "「企業が投下資本を上回る価値をどれだけ創造できたか」を示す指標"]\n    },\n    {\n      "fact": "MVA（市場価格調整）とは、市場金利の変動に伴う運用資産の価格の変動を解約返戻金に反映させる方法です。",\n      "substring_quote": ["MVA（市場価格調整）とは、市場金利の変動に伴う運用資産の価格の変動を解約返戻金に反映させる方法。"]\n    }\n  ]\n}', 'name': 'QuestionAnswer'}, 'type': 'function'}]}, response_metadata={'token_usage': {'completion_tokens': 582, 'prompt_tokens': 3283, 'total_tokens': 3865}, 'model_name': 'gpt-4', 'system_fingerprint': None, 'prompt_filter_results': [{'prompt_index': 0, 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}], 'finish_reason': 'tool_calls', 'logprobs': None, 'content_filter_results': {}}, id='run-3ff23784-eb36-4e2b-869d-6885fdff21f3-0', tool_calls=[{'name': 'QuestionAnswer', 'args': {'question': 'MVAについて説明してください。', 'answer': [{'fact': 'MVA（Market Value Added）は、投資家がその企業に対してどれだけの価値を認めているかを示します。これは、企業の市場価値（株価などによって決まる）と、その企業が実際に持っている資産の価値（会社の総資産）との差です。', 'substring_quote': ['MVA（Market Value Added：市場付加価値）', 'MVAは、投資家がその企業に対してどれだけの価値を認めているかを示します。これは、企業の市場価値（株価などによって決まる）と、その企業が実際に持っている資産の価値（会社の総資産）との差です。']}, {'fact': 'MVAは企業全体の市場価値から投下資本を差し引いた金額であり、「企業が投下資本を上回る価値をどれだけ創造できたか」を示す指標です。', 'substring_quote': ['Value Added：市場付加価値）', '・企業全体の市場価値から投下資本を差し引いた金額であり', '「企業が投下資本を上回る価値をどれだけ創造できたか」を示す指標']}, {'fact': 'MVA（市場価格調整）とは、市場金利の変動に伴う運用資産の価格の変動を解約返戻金に反映させる方法です。', 'substring_quote': ['MVA（市場価格調整）とは、市場金利の変動に伴う運用資産の価格の変動を解約返戻金に反映させる方法。']}]}, 'id': 'call_hrW3xO0IxFeCAMeIvFoWb1Sh'}], id_='c5fad471-8667-49d5-93fa-a7953e9321fe')])

**Comment by lone17** [comment]
@cin-kay would you be open to working on a PR for this one ?

**Comment by khankaholic** [comment]
already done, please help me to link this PR https://github.com/Cinnamon/kotaemon/pull/82 to this issue a @lone17

**Comment by lone17** [comment]
Update: citation is not working with gpt3.5 and is timed out with gpt4
